<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BankpaymentProduct', 'doctrine');

/**
 * BaseBankpaymentProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property float $price
 * @property integer $type
 * @property integer $is_active
 * @property string $group_name
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer            getId()         Returns the current record's "id" value
 * @method string             getCode()       Returns the current record's "code" value
 * @method string             getName()       Returns the current record's "name" value
 * @method float              getPrice()      Returns the current record's "price" value
 * @method integer            getType()       Returns the current record's "type" value
 * @method integer            getIsActive()   Returns the current record's "is_active" value
 * @method string             getGroupName()  Returns the current record's "group_name" value
 * @method timestamp          getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp          getUpdatedAt()  Returns the current record's "updated_at" value
 * @method BankpaymentProduct setId()         Sets the current record's "id" value
 * @method BankpaymentProduct setCode()       Sets the current record's "code" value
 * @method BankpaymentProduct setName()       Sets the current record's "name" value
 * @method BankpaymentProduct setPrice()      Sets the current record's "price" value
 * @method BankpaymentProduct setType()       Sets the current record's "type" value
 * @method BankpaymentProduct setIsActive()   Sets the current record's "is_active" value
 * @method BankpaymentProduct setGroupName()  Sets the current record's "group_name" value
 * @method BankpaymentProduct setCreatedAt()  Sets the current record's "created_at" value
 * @method BankpaymentProduct setUpdatedAt()  Sets the current record's "updated_at" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBankpaymentProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bankpayment_product');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('code', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('type', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('group_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}