<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VendorUser', 'doctrine');

/**
 * BaseVendorUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $vendor_id
 * @property string $username
 * @property string $password
 * @property Vendor $Vendor
 * 
 * @method integer    getVendorId()  Returns the current record's "vendor_id" value
 * @method string     getUsername()  Returns the current record's "username" value
 * @method string     getPassword()  Returns the current record's "password" value
 * @method Vendor     getVendor()    Returns the current record's "Vendor" value
 * @method VendorUser setVendorId()  Sets the current record's "vendor_id" value
 * @method VendorUser setUsername()  Sets the current record's "username" value
 * @method VendorUser setPassword()  Sets the current record's "password" value
 * @method VendorUser setVendor()    Sets the current record's "Vendor" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVendorUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vendor_user');
        $this->hasColumn('vendor_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('username', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('password', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vendor', array(
             'local' => 'vendor_id',
             'foreign' => 'id'));
    }
}