<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BankpaymentMobinet', 'doctrine');

/**
 * BaseBankpaymentMobinet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $bankpayment_id
 * @property integer $bundle
 * @property string $bundle_name
 * @property integer $speed
 * @property integer $extent_month
 * 
 * @method integer            getBankpaymentId()  Returns the current record's "bankpayment_id" value
 * @method integer            getBundle()         Returns the current record's "bundle" value
 * @method string             getBundleName()     Returns the current record's "bundle_name" value
 * @method integer            getSpeed()          Returns the current record's "speed" value
 * @method integer            getExtentMonth()    Returns the current record's "extent_month" value
 * @method BankpaymentMobinet setBankpaymentId()  Sets the current record's "bankpayment_id" value
 * @method BankpaymentMobinet setBundle()         Sets the current record's "bundle" value
 * @method BankpaymentMobinet setBundleName()     Sets the current record's "bundle_name" value
 * @method BankpaymentMobinet setSpeed()          Sets the current record's "speed" value
 * @method BankpaymentMobinet setExtentMonth()    Sets the current record's "extent_month" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBankpaymentMobinet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bankpayment_mobinet');
        $this->hasColumn('bankpayment_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('bundle', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('bundle_name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('speed', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('extent_month', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}