<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TransactionPayment', 'transaction');

/**
 * BaseTransactionPayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $transaction_id
 * @property integer $payment_id
 * @property Transaction $Transaction
 * @property Payment $Payment
 * @property Transaction $Transaction_3
 * @property Payment $Payment_4
 * @property Transaction $Transaction_5
 * @property Payment $Payment_6
 * @property Transaction $Transaction_7
 * @property Payment $Payment_8
 * @property Payment $Payment_9
 * @property Transaction $Transaction_10
 * @property Payment $Payment_11
 * @property Transaction $Transaction_12
 * @property Payment $Payment_13
 * @property Transaction $Transaction_14
 * @property Payment $Payment_15
 * @property Transaction $Transaction_16
 * 
 * @method integer            getId()             Returns the current record's "id" value
 * @method integer            getTransactionId()  Returns the current record's "transaction_id" value
 * @method integer            getPaymentId()      Returns the current record's "payment_id" value
 * @method Transaction        getTransaction()    Returns the current record's "Transaction" value
 * @method Payment            getPayment()        Returns the current record's "Payment" value
 * @method Transaction        getTransaction3()   Returns the current record's "Transaction_3" value
 * @method Payment            getPayment4()       Returns the current record's "Payment_4" value
 * @method Transaction        getTransaction5()   Returns the current record's "Transaction_5" value
 * @method Payment            getPayment6()       Returns the current record's "Payment_6" value
 * @method Transaction        getTransaction7()   Returns the current record's "Transaction_7" value
 * @method Payment            getPayment8()       Returns the current record's "Payment_8" value
 * @method Payment            getPayment9()       Returns the current record's "Payment_9" value
 * @method Transaction        getTransaction10()  Returns the current record's "Transaction_10" value
 * @method Payment            getPayment11()      Returns the current record's "Payment_11" value
 * @method Transaction        getTransaction12()  Returns the current record's "Transaction_12" value
 * @method Payment            getPayment13()      Returns the current record's "Payment_13" value
 * @method Transaction        getTransaction14()  Returns the current record's "Transaction_14" value
 * @method Payment            getPayment15()      Returns the current record's "Payment_15" value
 * @method Transaction        getTransaction16()  Returns the current record's "Transaction_16" value
 * @method TransactionPayment setId()             Sets the current record's "id" value
 * @method TransactionPayment setTransactionId()  Sets the current record's "transaction_id" value
 * @method TransactionPayment setPaymentId()      Sets the current record's "payment_id" value
 * @method TransactionPayment setTransaction()    Sets the current record's "Transaction" value
 * @method TransactionPayment setPayment()        Sets the current record's "Payment" value
 * @method TransactionPayment setTransaction3()   Sets the current record's "Transaction_3" value
 * @method TransactionPayment setPayment4()       Sets the current record's "Payment_4" value
 * @method TransactionPayment setTransaction5()   Sets the current record's "Transaction_5" value
 * @method TransactionPayment setPayment6()       Sets the current record's "Payment_6" value
 * @method TransactionPayment setTransaction7()   Sets the current record's "Transaction_7" value
 * @method TransactionPayment setPayment8()       Sets the current record's "Payment_8" value
 * @method TransactionPayment setPayment9()       Sets the current record's "Payment_9" value
 * @method TransactionPayment setTransaction10()  Sets the current record's "Transaction_10" value
 * @method TransactionPayment setPayment11()      Sets the current record's "Payment_11" value
 * @method TransactionPayment setTransaction12()  Sets the current record's "Transaction_12" value
 * @method TransactionPayment setPayment13()      Sets the current record's "Payment_13" value
 * @method TransactionPayment setTransaction14()  Sets the current record's "Transaction_14" value
 * @method TransactionPayment setPayment15()      Sets the current record's "Payment_15" value
 * @method TransactionPayment setTransaction16()  Sets the current record's "Transaction_16" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTransactionPayment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('transaction_payment');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('transaction_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('payment_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Transaction', array(
             'local' => 'transaction_id',
             'foreign' => 'id'));

        $this->hasOne('Payment', array(
             'local' => 'payment_id',
             'foreign' => 'id'));

        $this->hasOne('Transaction as Transaction_3', array(
             'local' => 'transaction_id',
             'foreign' => 'id'));

        $this->hasOne('Payment as Payment_4', array(
             'local' => 'payment_id',
             'foreign' => 'id'));

        $this->hasOne('Transaction as Transaction_5', array(
             'local' => 'transaction_id',
             'foreign' => 'id'));

        $this->hasOne('Payment as Payment_6', array(
             'local' => 'payment_id',
             'foreign' => 'id'));

        $this->hasOne('Transaction as Transaction_7', array(
             'local' => 'transaction_id',
             'foreign' => 'id'));

        $this->hasOne('Payment as Payment_8', array(
             'local' => 'payment_id',
             'foreign' => 'id'));

        $this->hasOne('Payment as Payment_9', array(
             'local' => 'payment_id',
             'foreign' => 'id'));

        $this->hasOne('Transaction as Transaction_10', array(
             'local' => 'transaction_id',
             'foreign' => 'id'));

        $this->hasOne('Payment as Payment_11', array(
             'local' => 'payment_id',
             'foreign' => 'id'));

        $this->hasOne('Transaction as Transaction_12', array(
             'local' => 'transaction_id',
             'foreign' => 'id'));

        $this->hasOne('Payment as Payment_13', array(
             'local' => 'payment_id',
             'foreign' => 'id'));

        $this->hasOne('Transaction as Transaction_14', array(
             'local' => 'transaction_id',
             'foreign' => 'id'));

        $this->hasOne('Payment as Payment_15', array(
             'local' => 'payment_id',
             'foreign' => 'id'));

        $this->hasOne('Transaction as Transaction_16', array(
             'local' => 'transaction_id',
             'foreign' => 'id'));
    }
}