<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VendorIp', 'doctrine');

/**
 * BaseVendorIp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $vendor_id
 * @property string $ip_address
 * @property Vendor $Vendor
 * 
 * @method integer  getId()         Returns the current record's "id" value
 * @method integer  getVendorId()   Returns the current record's "vendor_id" value
 * @method string   getIpAddress()  Returns the current record's "ip_address" value
 * @method Vendor   getVendor()     Returns the current record's "Vendor" value
 * @method VendorIp setId()         Sets the current record's "id" value
 * @method VendorIp setVendorId()   Sets the current record's "vendor_id" value
 * @method VendorIp setIpAddress()  Sets the current record's "ip_address" value
 * @method VendorIp setVendor()     Sets the current record's "Vendor" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVendorIp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vendor_ip');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('vendor_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip_address', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Vendor', array(
             'local' => 'vendor_id',
             'foreign' => 'id'));
    }
}