<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BankpaymentVat', 'doctrine');

/**
 * BaseBankpaymentVat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $bankpayment_id
 * @property integer $status
 * @property integer $type
 * @property integer $outcome_order_id
 * 
 * @method integer        getBankpaymentId()    Returns the current record's "bankpayment_id" value
 * @method integer        getStatus()           Returns the current record's "status" value
 * @method integer        getType()             Returns the current record's "type" value
 * @method integer        getOutcomeOrderId()   Returns the current record's "outcome_order_id" value
 * @method BankpaymentVat setBankpaymentId()    Sets the current record's "bankpayment_id" value
 * @method BankpaymentVat setStatus()           Sets the current record's "status" value
 * @method BankpaymentVat setType()             Sets the current record's "type" value
 * @method BankpaymentVat setOutcomeOrderId()   Sets the current record's "outcome_order_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBankpaymentVat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bankpayment_vat');
        $this->hasColumn('bankpayment_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('type', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('outcome_order_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}