<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Vendor', 'doctrine');

/**
 * BaseVendor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $parent_id
 * @property string $name
 * @property integer $source_code
 * @property integer $status
 * @property timestamp $updated_at
 * @property timestamp $created_at
 * @property Doctrine_Collection $Vendor
 * @property Doctrine_Collection $VendorIp
 * @property Doctrine_Collection $VendorUser
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getParentId()    Returns the current record's "parent_id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method integer             getSourceCode()  Returns the current record's "source_code" value
 * @method integer             getStatus()      Returns the current record's "status" value
 * @method timestamp           getUpdatedAt()   Returns the current record's "updated_at" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method Doctrine_Collection getVendor()      Returns the current record's "Vendor" collection
 * @method Doctrine_Collection getVendorIp()    Returns the current record's "VendorIp" collection
 * @method Doctrine_Collection getVendorUser()  Returns the current record's "VendorUser" collection
 * @method Vendor              setId()          Sets the current record's "id" value
 * @method Vendor              setParentId()    Sets the current record's "parent_id" value
 * @method Vendor              setName()        Sets the current record's "name" value
 * @method Vendor              setSourceCode()  Sets the current record's "source_code" value
 * @method Vendor              setStatus()      Sets the current record's "status" value
 * @method Vendor              setUpdatedAt()   Sets the current record's "updated_at" value
 * @method Vendor              setCreatedAt()   Sets the current record's "created_at" value
 * @method Vendor              setVendor()      Sets the current record's "Vendor" collection
 * @method Vendor              setVendorIp()    Sets the current record's "VendorIp" collection
 * @method Vendor              setVendorUser()  Sets the current record's "VendorUser" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVendor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vendor');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('parent_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('source_code', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Vendor', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $this->hasMany('VendorIp', array(
             'local' => 'id',
             'foreign' => 'vendor_id'));

        $this->hasMany('VendorUser', array(
             'local' => 'id',
             'foreign' => 'vendor_id'));
    }
}