<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Block', 'doctrine');

/**
 * BaseBlock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $bank_id
 * @property integer $block
 * @property integer $updated_user_id
 * @property timestamp $updated_at
 * 
 * @method integer   getId()              Returns the current record's "id" value
 * @method integer   getBankId()          Returns the current record's "bank_id" value
 * @method integer   getBlock()           Returns the current record's "block" value
 * @method integer   getUpdatedUserId()   Returns the current record's "updated_user_id" value
 * @method timestamp getUpdatedAt()       Returns the current record's "updated_at" value
 * @method Block     setId()              Sets the current record's "id" value
 * @method Block     setBankId()          Sets the current record's "bank_id" value
 * @method Block     setBlock()           Sets the current record's "block" value
 * @method Block     setUpdatedUserId()   Sets the current record's "updated_user_id" value
 * @method Block     setUpdatedAt()       Sets the current record's "updated_at" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlock extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('block');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('bank_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('block', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('updated_user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}