<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BankpaymentTransferrule', 'doctrine');

/**
 * BaseBankpaymentTransferrule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $c_rule
 * @property integer $c_sequence
 * @property string $c_action
 * @property string $c_param
 * @property string $c_description
 * 
 * @method string                  getCRule()         Returns the current record's "c_rule" value
 * @method integer                 getCSequence()     Returns the current record's "c_sequence" value
 * @method string                  getCAction()       Returns the current record's "c_action" value
 * @method string                  getCParam()        Returns the current record's "c_param" value
 * @method string                  getCDescription()  Returns the current record's "c_description" value
 * @method BankpaymentTransferrule setCRule()         Sets the current record's "c_rule" value
 * @method BankpaymentTransferrule setCSequence()     Sets the current record's "c_sequence" value
 * @method BankpaymentTransferrule setCAction()       Sets the current record's "c_action" value
 * @method BankpaymentTransferrule setCParam()        Sets the current record's "c_param" value
 * @method BankpaymentTransferrule setCDescription()  Sets the current record's "c_description" value
 * 
 * @package    BANKGW
 * @subpackage model
 * @author     Belbayar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBankpaymentTransferrule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bankpayment_transferrule');
        $this->hasColumn('c_rule', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('c_sequence', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('c_action', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('c_param', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('c_description', 'string', 450, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 450,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}