<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BankSavingsAccount', 'doctrine');

/**
 * BaseBankSavingsAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $account
 * @property string $pin
 * @property date $start_date
 * @property date $end_date
 * @property timestamp $created_at
 * 
 * @method integer            getId()         Returns the current record's "id" value
 * @method string             getName()       Returns the current record's "name" value
 * @method string             getAccount()    Returns the current record's "account" value
 * @method string             getPin()        Returns the current record's "pin" value
 * @method date               getStartDate()  Returns the current record's "start_date" value
 * @method date               getEndDate()    Returns the current record's "end_date" value
 * @method timestamp          getCreatedAt()  Returns the current record's "created_at" value
 * @method BankSavingsAccount setId()         Sets the current record's "id" value
 * @method BankSavingsAccount setName()       Sets the current record's "name" value
 * @method BankSavingsAccount setAccount()    Sets the current record's "account" value
 * @method BankSavingsAccount setPin()        Sets the current record's "pin" value
 * @method BankSavingsAccount setStartDate()  Sets the current record's "start_date" value
 * @method BankSavingsAccount setEndDate()    Sets the current record's "end_date" value
 * @method BankSavingsAccount setCreatedAt()  Sets the current record's "created_at" value
 * 
 * @package    BANKGW
 * @subpackage model
 * @author     Belbayar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBankSavingsAccount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bank_savings_account');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('account', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('pin', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('start_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('end_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}