<?php

/**
 * BankpaymentProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BankpaymentProductTable extends Doctrine_Table
{

    const ACTIVE = 1;

    /**
     * Returns an instance of this class.
     *
     * @return object BankpaymentProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BankpaymentProduct');
    }

    /**
     * Product object
     *
     * @param int $pk
     * @param string $fields
     * @return Product
     */
    public static function retrieveByPK($pk)
    {
        $q = Doctrine_Query::create()
                ->from('BankpaymentProduct')
                ->where('id =?', $pk)
                ->limit(1);
        return $q->fetchOne();
    }

    /**
     * Product object
     *
     * @param int $pk
     * @param string $fields
     * @return Product
     */
    public static function findByPrice($price)
    {
        $q = Doctrine_Query::create()
                ->from('BankpaymentProduct')
                ->where('price =?', $price)
                ->addWhere('is_active=?', self::ACTIVE)
                ->limit(1);
        return $q->fetchOne();
    }

    /**
     * 
     * @return \
     */
    public static function getList()
    {
        $q = Doctrine_Query::create()
                ->from('BankpaymentProduct');

        return $q->execute();
    }

}
