<?php

/**
 * Bankpayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Bankpayment extends BaseBankpayment
{

    public function canReCharge()
    {
        if (in_array($this->status, array(
                    BankpaymentTable::STAT_PROCESS,
                    BankpaymentTable::STAT_FAILED_BILL_INFO,
                    BankpaymentTable::STAT_FAILED_CHARGE,
                    BankpaymentTable::STAT_BANKPAYMENT_AMOUNT,
                    BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE))) {

            return TRUE;
        }
        return FALSE;
    }

}
