<?php

/**
 * BankCapitronAccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BankCapitronAccountTable extends Doctrine_Table
{

    CONST ACCOUNT_CALLPAYMENT = '3096000540';
    CONST ACCOUNT_MOBINET_PAYMENT = '';
    /**
     * Returns an instance of this class.
     *
     * @return object BankKhaanAccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BankCapitronAccount');
    }

    /**
     * Payment code
     *
     * @return object BankCapitronAccountTable
     */
    public static function getPaymentCode($account)
    {
        $code = 0;
        switch ($account) {
            case self::ACCOUNT_CALLPAYMENT:
                $code = 'CNKR7';
                break;
            default:
                break;
        }
        return $code;
    }
}