<?php

/**
 * BankSavingsLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BankSavingsLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BankSavingsLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BankSavingsLog');
    }
}