<?php

/**
 * BankTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BankTable extends Doctrine_Table
{

    const ACTIVE = 1;
    #
    const KHAAN = 1;
    const GOLOMT = 2;
    const XAC = 3;
    const TDB = 4;
    const CAPITAL = 8;
    const SAVINGS = 9;
    const MOBIXPRESS = 10;
    const CANDY = 11;
    const CAPITRON = 12;

    /**
     * Returns an instance of this class.
     *
     * @return object BankTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bank');
    }

    public static function getForSelect()
    {
        $q = Doctrine_Query::create()
                ->from('Bank')
                ->where('status = ?', self::ACTIVE);
        $banks = $q->execute();
        $arr = array();
        foreach ($banks as $bank) {
            $arr[$bank['id']] = $bank['name'];
        }
        return $arr;
    }

    public static function getBankAndVendorMap($vendorId)
    {
        switch ($vendorId) {
            case VendorTable::GOLOMT:
                $bankId = self::GOLOMT;
                break;
            case VendorTable::BANK_SAVINGS:
                $bankId = self::SAVINGS;
                break;
            case VendorTable::BANK_KHAAN:
                $bankId = self::KHAAN;
                break;
            case VendorTable::BANK_XAC:
                $bankId = self::XAC;
                break;
            case VendorTable::BANK_TDB:
                $bankId = self::TDB;
                break;
            case VendorTable::BANK_CAPITAL:
                $bankId = self::CAPITAL;
                break;
            case VendorTable::BANK_CAPITRON:
                $bankId = self::CAPITRON;
                break;
            default:
                $bankId = 0;
                break;
        }
        return $bankId;
    }

}
