<?php

/**
 * BankpaymentTransfertypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BankpaymentTransfertypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BankpaymentTransfertypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BankpaymentTransfertype');
    }
}