<?php

/**
 * BankKhaanLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BankKhaanLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BankKhaanLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BankKhaanLog');
    }
}