<?php

/**
 * BankpaymentMobinetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BankpaymentMobinetTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object BankpaymentMobinetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BankpaymentMobinet');
    }

    /**
     * 
     * @param int $id
     * @param int $status
     * @return Bankpayment
     */
    public static function retrieveByPK($id)
    {
        $q = Doctrine_Query::create()
                ->from('BankpaymentMobinet')
                ->where('bankpayment_id = ?', $id);

        return $q->fetchOne();
    }

    /**
     * 
     * @param array $trans
     * @return Bankpayment|null
     */
    public static function getSpeed($id)
    {
        $q = Doctrine_Query::create()
                ->from('BankpaymentMobinet')
                ->where('bankpayment_id = ?', $id);
        $mobinet = $q->fetchOne();

        return $mobinet->getSpeed();
    }

    /**
     * 
     * @param array $trans
     * @return Bankpayment|null
     */
    public static function updateBundleMonth($id, $month, $bundle)
    {
        $object = self::retrieveByPK($id);
        if ($object) {
            $object->setExtentMonth($month);
            $object->setBundleName($bundle);
            $object->save();
        }
    }

    /**
     * 
     * @param array $trans
     * @return Bankpayment|null
     */
    public static function insert($bankpaymentId, $speed, $bundle = 0, $bundleName = '')
    {
        try {
            $bankPayment = self::retrieveByPK($bankpaymentId);
            if (!$bankPayment) {
                $bankPayment = new BankpaymentMobinet();
                $bankPayment->bankpayment_id = (int) $bankpaymentId;
            }
            $bankPayment->speed = (int) $speed;
            $bankPayment->bundle = $bundle;
            $bankPayment->bundle_name = $bundleName;
            $bankPayment->save();
            return $bankPayment;
        } catch (Exception $exc) {
//            $logger = new sfFileLogger(new sfEventDispatcher(), array('file' => sfConfig::get('sf_log_dir') . '/bankpayment.log'));
//            $logger->log("error", sfFileLogger::ERR);
        }
        return FALSE;
    }

}
