<?php

/**
 * BankMergeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BankMergeTable extends Doctrine_Table
{

    const TYPE_CHARGE = 1;

    /**
     * Returns an instance of this class.
     *
     * @return object BankMergeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BankMerge');
    }

    /**
     * 
     * @param array $trans
     * @return Bankpayment|null
     */
    public static function insert($type, $userId)
    {
        $object = new BankMerge();
        $object->setType($type);
        $object->setCreatedUser($userId);
        $object->setCreatedAt(date('Y-m-d H:i:s'));
        $object->save();
        return $object;
    }

}
