<?php

/**
 * BankCapitalAccountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BankCapitalAccountTable extends Doctrine_Table
{

    CONST ACCOUNT_DEALER = '0';
    CONST ACCOUNT_DEALER_MOBICOM = '';
    CONST ACCOUNT_CALLPAYMENT = '2200000222';
    CONST ACCOUNT_MOBINET_PAYMENT = '';
    CONST ACCOUNT_PRODUCT_PAYMENT = '';
    CONST ACCOUNT_PRODUCT_MOBINET = '';
    CONST ACCOUNT_PRODUCT_ULUSNET = '';
    CONST ACCOUNT_PRODUCT_BAG = '';
    CONST ACCOUNT_MOBIFINANCE_CANDY = '';

    /**
     * Returns an instance of this class.
     *
     * @return object BankCapitalAccountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BankCapitalAccount');
    }

    /**
     * Payment code
     *
     */
    public static function getPaymentCode($account)
    {
        $code = 0;
        switch ($account) {
            case self::ACCOUNT_MOBINET_PAYMENT:
                $code = '0';
                break;
            case self::ACCOUNT_CALLPAYMENT:
                $code = 'CNK2Z';
                break;
            default:
                break;
        }
        return $code;
    }

}
