<?php

/**
 * BankGolomt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BankGolomt extends BaseBankGolomt
{
    public function canReCharge()
    {
        if (in_array($this->status, array(
                    BankGolomtTable::STAT_FAILED,
                    BankGolomtTable::STAT_PROCESS,
                    BankGolomtTable::STAT_FAILED_CHARGE,
                    BankGolomtTable::STAT_FAILED_DEALER)) &&
                $this->try_count < BankGolomtTable::MAX_TRY_COUNT) {
            return TRUE;
        }

        return FALSE;
    }

    public function canReOutcome()
    {
        if (in_array($this->status, array(
                    BankGolomtTable::STAT_FAILED_OUTCOME
                ))) {
            return TRUE;
        }

        return FALSE;
    }
}