<?php

/**
 * BankSavingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BankSavingsTable extends Doctrine_Table
{

    const STAT_NEW = 1;
    const STAT_PROCESS = 2;
    const STAT_SUCCESS = 3;
    const STAT_FAILED_CHARGE = 4;
    const STAT_FAILED_OUTCOME = 5;
    const STAT_FAILED_DEALER = 6;
    const STAT_FAILED = 7;
    const STAT_FAILED_MAX_AMOUNT = 8;
    const STAT_FAILED_DUPLICATE_AMOUNT = 9;
    const STAT_FAILED_MIN_AMOUNT = 10;
    const STAT_WAIT_TEMP = 11;
    const STAT_CORRECTION = 12;
    const STAT_TRANS_VALUE_WRONG = 13;
    const STAT_CORRECTION_SUCCESS = 14;
    const STAT_CORRECTION_FAILED = 15;
    const MAX_TRY_COUNT = 3;
    const MAX_AMOUNT_LIMIT = 99999999;
    const MIN_AMOUNT_LIMIT = 28800;
//    const SAVINGS_URL = 'http://202.131.225.152:89/MobiService.asmx?WSDL';
//    const SAVINGS_URL = 'http://202.131.225.152:89/Statement.asmx?wsdl';
    #old const SAVINGS_URL = 'http://192.168.20.36:8095/mobidealer/Statement.asmx?wsdl';
    const SAVINGS_URL = 'http://192.168.100.35:8095/mobidealer/Statement.asmx?wsdl';
    ##
    CONST ACCOUNT_MOBINET_PAYMENT = '102200117836';
    CONST ACCOUNT_CALLPAYMENT = '100000139627';
    CONST ACCOUNT_PRODUCT_MOBINET = '102200117820';
    CONST ACCOUNT_MOBIFINANCE_CANDY = '106900331147';
    CONST TYPE_DEALER = 1;

    # mobixpress account

    /**
     * Returns an instance of this class.
     *
     * @return object BankSavingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BankSavings');
    }

    /**
     * 
     * @param int $id
     * @param int $status
     * @return BankSavings
     */
    public static function retrieveByPK($id, $status = 0)
    {
        $q = Doctrine_Query::create()
                ->from('BankSavings')
                ->where('id = ?', $id);

        if ($status) {
            $q->andWhere('status = ?', $status);
        }

        return $q->fetchOne();
    }

    /**
     *
     * @param int $orderId
     * @param int $orderIdSub
     * @return BankSavings
     */
    public static function findOneByOrderId($orderId, $orderIdSub = 0)
    {
        $q = Doctrine_Query::create()
                ->from('BankSavings')
                ->where('order_id = ?', $orderId);
        if ($orderIdSub) {
            $q->addWhere('order_id_sub = ?', $orderIdSub);
        }

        return $q->fetchOne();
    }

    /**
     *
     * @param int $orderId
     * @return Doctrine_Collection
     * @throws Doctrine_Query_Exception
     */
    public static function setReturn($orderId)
    {
        return Doctrine_Query::create()
                        ->update('BankSavings')
                        ->set('status', self::STAT_CORRECTION)
                        ->where('order_id = ?', $orderId)
                        ->addWhere('status = ?', self::STAT_NEW)
                        ->execute();
    }

    /**
     *
     * @param bool $excel
     * @param int $account
     * @return \sfDoctrinePager
     * @throws Doctrine_Query_Exception
     * @throws sfException
     */
    public static function getList($excel = false, $account = 1)
    {
        $q = Doctrine_Query::create()
                ->from('BankSavings')
                ->where('vendor_id = ?', VendorCore::BANK_SAVINGS)
                ->orderBy('status DESC, id DESC');

        $request = sfContext::getInstance()->getRequest();

        // mandatory
        $dateFrom = $request->getParameter('dateFrom') ? $request->getParameter('dateFrom') : date('Y-m-d');
        $dateTo = $request->getParameter('dateTo') ? $request->getParameter('dateTo') : date('Y-m-d');
        $q->addWhere("created_at >= ?", $dateFrom . " 00:00:00");
        $q->addWhere("created_at <= ?", $dateTo . " 23:59:59");

        // optional
        $chargedMobile = (int) $request->getParameter('chargedMobile');
        if ($chargedMobile) {
            $q->addWhere('charge_mobile = ?', $chargedMobile);
        }

        // optional
        $orderedMobile = (int) $request->getParameter('orderedMobile');
        if ($orderedMobile) {
            $q->addWhere('order_mobile = ?', $orderedMobile);
        }
        if (is_array($account)) {
            $q->andWhereIn('bank_account', $account);
        } else {
            $q->addWhere('bank_account = ?', $account);
        }
        // optional
        $orderId = $request->getParameter('orderId');
        if ($orderId) {
            $q->addWhere('order_id = ?', $orderId);
        }

        // optional
        $status = (int) $request->getParameter('status');
        if ($status) {
            $q->addWhere('status = ?', $status);
        }
        if ($excel) {
            return $q->execute();
        }

        // pager
        $page = (int) $request->getParameter('page', 1);

        $pager = new sfDoctrinePager('BankSavings', 100);
        $pager->setQuery($q);
        $pager->setPage($page);
        $pager->init();

        return $pager;
    }

    /**
     * Төлөв
     *
     * @param $type
     * @return array
     */
    public static function getForSelectStatus($type)
    {
        switch ($type) {
            case BankSavingsAccountTable::ACCOUNT_DEALER:
                $status = array(
                    self::STAT_NEW => 'Шинэ хуулга',
                    self::STAT_PROCESS => 'Цэнэглэж байна',
                    self::STAT_SUCCESS => 'Амжилттай цэнэглэсэн',
                    self::STAT_FAILED_CHARGE => 'Цэнэглэлт хийгдсэнгүй',
                    self::STAT_FAILED_OUTCOME => 'Зарлага хийгдсэнгүй',
                    self::STAT_FAILED_DEALER => 'Гэрээт олдсонгүй',
                    self::STAT_FAILED => 'Алдаа гарсан',
                    self::STAT_FAILED_MAX_AMOUNT => 'Их хэмжээний дүнтэй',
                    self::STAT_FAILED_DUPLICATE_AMOUNT => 'Ижил хэмжээний үнийн дүнтэй цэнэглэлт/баталгаажуулах/',
                    self::STAT_FAILED_MIN_AMOUNT => 'Цэнэглэх доод хязгаараас бага дүнтэй',
                );
                break;
            case BankSavingsAccountTable::ACCOUNT_CALLPAYMENT:
                $status = array(
                    self::STAT_NEW => 'Шинэ хуулга',
                    self::STAT_PROCESS => 'Төлөлт оруулж байна',
                    self::STAT_SUCCESS => 'Амжилттай төлөлт оруулсан',
                    self::STAT_FAILED_CHARGE => 'Төлөлт оруулсангүй',
                    self::STAT_FAILED => 'Алдаа гарсан',
                );
                break;
            case BankSavingsAccountTable::ACCOUNT_MOBIXPRESS:
                $status = array(
                    self::STAT_NEW => 'Шинэ хуулга',
                    self::STAT_PROCESS => 'Төлөлт оруулж байна',
                    self::STAT_SUCCESS => 'Амжилттай төлөлт оруулсан',
                    self::STAT_FAILED_CHARGE => 'Төлөлт оруулсангүй',
                    self::STAT_FAILED => 'Алдаа гарсан',
                );
                break;
        }
        return $status;
    }

    /**
     * Төлвийн нэр
     *
     * @param int $v
     * @param int $type
     * @param boolean $img
     * @return string
     */
    public static function getStatusName($v, $type = 1, $img = false)
    {
        $v = (int) $v;

        $arr = self::getForSelectStatus($type);

        if (!isset($arr[$v])) {
            return '#';
        }

        if (!$img) {
            return $arr[$v];
        }

        $attr = 'title="' . $arr[$v] . '" alt="' . $arr[$v] . '"';

        switch ($v) {
            case self::STAT_NEW:
                return '<img src="/images/icons/info.png" ' . $attr . ' />';
            case self::STAT_PROCESS:
                return '<img src="/images/icons/process.png" ' . $attr . ' />';
            case self::STAT_FAILED_OUTCOME:
                return '<img src="/images/icons/warning.png" ' . $attr . ' />';
            case self::STAT_SUCCESS:
                return '<img src="/images/icons/save.png" ' . $attr . ' />';
            case self::STAT_FAILED_CHARGE:
                return '<img src="/images/icons/error.png" ' . $attr . ' />';
            case self::STAT_FAILED_DEALER:
                return '<img src="/images/icons/user_delete.png" ' . $attr . ' />';
            case self::STAT_FAILED:
                return '<img src="/images/icons/error.png" ' . $attr . ' />';
            case self::STAT_FAILED_MAX_AMOUNT:
                return '<img src="/images/icons/world.png" ' . $attr . ' />';
            case self::STAT_FAILED_MIN_AMOUNT:
                return '<img src="/images/icons/world.png" ' . $attr . ' />';
            case self::STAT_WAIT_TEMP:
                return '<img src="/images/icons/wait.png" ' . $attr . ' />';
            case self::STAT_CORRECTION:
                return '<img src="/images/icons/wait.png" ' . $attr . ' />';
            case self::STAT_TRANS_VALUE_WRONG:
                return '<img src="/images/icons/error.png" ' . $attr . ' />';
            default :
                return '#';
        }
    }

    /**
     * 
     * @param array $trans
     * @return BankSavings|null
     */
    public static function insertFromTrans($trans)
    {
        $bankOrder = new BankSavings();
        $bankOrder->order_id = $trans['JrNo'];
        $bankOrder->order_id_sub = $trans['JrItemNo'];
        $bankOrder->bank_account = $trans['AcntNo'];
        $bankOrder->order_p = $trans['TxnDesc'];
        $bankOrder->order_type = ($trans['TxnType']) ? 'ADD' : 'SUB';
        $bankOrder->order_amount = $trans['Amount'];
        $bankOrder->order_date = $trans['TxnDate'];
        $return = $trans['Corr'];
        $bankOrder->order_s = $trans['BranchNo'] . '-' . $trans['Location'];
        $bankOrder->status = self::STAT_NEW;
        $bankOrder->vendor_id = VendorCore::BANK_SAVINGS;
        $bankOrder->created_at = date('Y-m-d H:i:s');
        $account = $trans['AcntNo'];
        if ($return) {
            if (self::setReturn($return)) {
                $bankOrder->status = self::STAT_CORRECTION_SUCCESS;
            } else {
                $bankOrder->status = self::STAT_CORRECTION_FAILED;
            }
        }
        switch ($account) {
            case BankSavingsAccountTable::ACCOUNT_MOBIXPRESS:
                $transactionInfo = explode('-', $trans['TxnDesc']);
                if ($transactionInfo[0] == 'MX' || $transactionInfo[0] == 'МХ') {
                    $bankOrder->charge_mobile = (int) $transactionInfo[1];
                    $bankOrder->order_mobile = (int) $transactionInfo[2];
                } else {
                    $bankOrder->status = self::STAT_TRANS_VALUE_WRONG;
                }
                break;
            case BankSavingsAccountTable::ACCOUNT_DEALER:
                $txnDesc = preg_replace("/\([0-9]{8}\)/", "", $trans['TxnDesc']);
                preg_match_all("/([9][954][0-9]{6})|(85[0-9]{6})/", $txnDesc, $matches);
                foreach ($matches as $numberArr) {
                    foreach ($numberArr as $number) {
                        $number = trim($number);
                        if ($number) {
                            $bankOrder->order_mobile = $number;
                            $bankOrder->charge_mobile = $number;
                            continue;
                        }
                    }
                }
                break;
            case BankSavingsAccountTable::ACCOUNT_CALLPAYMENT:
                $txnDesc = preg_replace("/\([0-9]{8}\)/", "", $trans['TxnDesc']);
                preg_match_all("/[9][954][0-9]{6}/", $txnDesc, $matches);
                foreach ($matches as $numberArr) {
                    foreach ($numberArr as $number) {
                        $number = trim($number);
                        $bankOrder->order_mobile = $number;
                        $bankOrder->charge_mobile = $number;
                        continue;
                    }
                }
                break;
            case BankSavingsAccountTable::ACCOUNT_CANDY_LOAN:
                $txnDesc = preg_replace("/\([0-9]{8}\)/", "", $trans['TxnDesc']);
                preg_match_all("/([9][954][0-9]{6})|(85[0-9]{6})/", $txnDesc, $matches);
                foreach ($matches as $numberArr) {
                    foreach ($numberArr as $number) {
                        $number = trim($number);
                        if ($number) {
                            $bankOrder->order_mobile = $number;
                            $bankOrder->charge_mobile = $number;
                            continue;
                        }
                    }
                }
                break;
            default:
                break;
        }
        try {
            $bankOrder->save();
        } catch (\Exception $exc) {
//            $banks = BankSavingsTable::findOneByOrderId($trans['JrNo'], 0);
//            if ($banks) {
//                $banks->setOrderIdSub($trans['JrItemNo']);
//                $banks->setTransferBank(0);
//                $banks->save();
//            }
            $logger = new sfFileLogger(new sfEventDispatcher(), array('file' => sfConfig::get('sf_log_dir') . '/my-savings-order.log'));
            $logger->log('--ERROR--=' . trim($trans['JrNo']) . $trans['JrItemNo'] . $exc->getMessage(), sfFileLogger::INFO);
        }


        return $bankOrder;
    }

    /**
     * Хуулга татах
     *
     * @param $soapUrl
     * @param $username
     * @param $password
     * @param $account
     * @param $date
     * @return boolean
     * @throws SoapFault
     */
    public static function init($soapUrl, $username, $password, $account, $date)
    {
//        error_reporting(0);
        $client = new SoapClient($soapUrl, array('trace' => 1, 'encoding' => 'utf-8', 'exceptions' => 1, 'wsdl_cache' => 0));

        $getSuccess = 0;
        $setSuccess = 0;
        $errorCode = -1;
        $desc = 'None';

        try {
            $pinToDecrypt = $account['pin'];
            $pin = AppTools::passDecrypt($pinToDecrypt);

            $params = array(
                'username' => $username,
                'pass' => $password,
                'acntNo' => $account['account'],
                'pin' => $pin,
                'txnDate' => $date,
            );
            $transIds = self::getTransIds();
            if (count($transIds)) {
                $params['reList'] = $transIds;
            }
            $result = $client->__call('GetStatement', array('parameters' => $params));

            $getSuccess = 1;
        } catch (SoapFault $e) {
            $desc = $e->faultstring;
        }
        $params['pin'] = "*****";
        $params['pass'] = "*****";
        $request = print_r($params, true);
        $response = '';
        $responseSet = '';

        $resultArr = json_decode(json_encode($result), true);

        if (isset($resultArr['GetStatementResult'])) {
            $response = print_r($result, true);
            $resultArr = $resultArr['GetStatementResult'];
            $errorCode = $resultArr['code'];
            $desc = "-" . $resultArr['msg'];
        }

        // хоосон утга шалгах
        if ($errorCode == 0 && isset($resultArr['list']['TxnItem']) && count($resultArr['list']['TxnItem'])) {
            // хуулга татах
            if (isset($resultArr['list']['TxnItem'][0])) {
                foreach ($resultArr['list']['TxnItem'] as $trans) {
                    $bankOrder = BankSavingsTable::findOneByOrderId(trim($trans['JrNo']), trim($trans['JrItemNo']));
                    if (!$bankOrder) {
                        $bankOrder = BankSavingsTable::insertFromTrans($trans);
                    }
                }
            } else {
                $bankOrder = BankSavingsTable::findOneByOrderId(trim($resultArr['list']['TxnItem']['JrNo']), trim($resultArr['list']['TxnItem']['JrItemNo']));
                if (!$bankOrder) {
                    $bankOrder = BankSavingsTable::insertFromTrans($resultArr['list']['TxnItem']);
                }
            }
        }

        LogTools::setLogSavingsInit($request, $response, $responseSet, $errorCode, $desc, $getSuccess, $setSuccess, $username);

        unset($result);
        unset($response);
        unset($responseSet);
        unset($resultArr);
        unset($trans);
        unset($client);

        return TRUE;
    }

    /**
     * Татсан хуулгын ID авах
     *
     * @return array
     */
    public static function getTransIds()
    {
        $q = Doctrine_Query::create()
                ->select('order_id,order_id_sub')
                ->from('BankSavings')
                ->where('transfer_bank = 0')
                ->limit(150);
        $results = $q->fetchArray();
        $result = array();
        foreach ($results as $tran) {
            $ids[] = $tran['id'];
            $arr['JrNo'] = $tran['order_id'];
            $arr['JrItemNo'] = $tran['order_id_sub'];
            $result[] = $arr;
        }
        try {
            if (isset($ids) && count($ids)) {
                $pdo = Doctrine_Manager::connection()->getDbh();
                $sql = "UPDATE bankgw.bank_savings
              SET transfer_bank = 1
              WHERE id IN (" . implode(',', $ids) . ")";
                $pdo->exec($sql);
            }
        } catch (\Exception $exc) {
            echo $exc->getTraceAsString();
        }



        return $result;
    }

    /**
     * Дахин цэнэглэлт
     *
     * @param null $bankOrder
     * @param int $limit
     * @return boolean
     * @throws Doctrine_Manager_Exception
     * @throws Doctrine_Query_Exception
     */
    public static function recharge($bankOrder = null, $limit = 50)
    {
        $customer = FALSE;
        if ($bankOrder instanceof BankSavings) {
            if ($bankOrder->canReCharge()) {
                $bankOrder->status = self::STAT_PROCESS;
                $bankOrder->save();
                $customer = TRUE;
            }
            $bankOrderRows = array($bankOrder);
        } elseif ($bankOrder) {
            return FALSE;
        } else {
            $bankOrderRows = self::updateForCharge(array(BankSavingsAccountTable::ACCOUNT_DEALER), 'ADD', $limit);
        }

        foreach ($bankOrderRows as $bankOrder) {
            try {
                $SD = $ADshop = FALSE;
                $chargeResult = $adCode = null;
                if (in_array($bankOrder->status, array(self::STAT_FAILED_CHARGE, self::STAT_FAILED))) {
                    $bankOrder->status = self::STAT_PROCESS;
                    $bankOrder->save();
                }
                if ($bankOrder->status == self::STAT_PROCESS) {
                    $bankOrder->try_count++;
                    $dealer = false;
                    # Dealer AGENT check
                    $logger = new sfFileLogger(new sfEventDispatcher(), array('file' => sfConfig::get('sf_log_dir') . '/dealer/process-' . date("Ymd") . '.log'));
                    $dealerAgent = DealerGateway::findDealerByMobile($bankOrder->charge_mobile, $logger);
//                    print_r($dealerAgent);die();
                    if (!$dealerAgent) {
                        $dealer = DealerCharge::getDealer($bankOrder->charge_mobile);
                        if (BaseSms::isSdDealer($bankOrder->order_p)) {
                            $SD = TRUE;
                        } else {
                            $adCode = BaseSms::isAdShop($bankOrder->order_p);
                            if ($adCode) {
                                $ADshop = TRUE;
                            } else {
                                # If the charge amount exceeds the max amount limit
                                if ($bankOrder->order_amount > self::MAX_AMOUNT_LIMIT) {
                                    $bankOrder->status = self::STAT_FAILED_MAX_AMOUNT;
                                    $bankOrder->save();
                                    self::notifyOperators($bankOrder);
                                    continue;
                                } elseif ($bankOrder->order_amount < self::MIN_AMOUNT_LIMIT) {
                                    $bankOrder->status = self::STAT_FAILED_MIN_AMOUNT;
                                    $bankOrder->save();
                                    self::notifyOperators($bankOrder);
                                    continue;
                                }
                            }
                        }
                    }
                    if ($dealerAgent || $dealer || $adCode) {
                        $logId = LogTools::setLogSavingsCharge($bankOrder->id);
                        $orderMobile = null;
                        unset($chargeResult);
                        $time = -time();
                        # Цэнэглэлт хийх
                        if ($SD) {
                            $chargeResult = BaseSms::chargeSdDealer($bankOrder->charge_mobile, $bankOrder->order_amount, 'STATE');
                        } elseif ($ADshop) {
                            $chargeResult = BaseSms::chargeAdDealer($adCode, $bankOrder->order_amount, 'STATE');
                        } elseif ($dealerAgent) {
                            $chargeResult = DealerGateway::charge($dealerAgent['dealerId'], $bankOrder->order_amount, 'STATE', $logger);
                            $orderMobile = $dealerAgent['dealerCode'];
                        } else {
                            $chargeResult = DealerCharge::charge($bankOrder->charge_mobile, $bankOrder->order_amount);
                        }
                        $time += time();

                        LogTools::updateLogSavingsCharge($logId, $chargeResult['log_request'], $chargeResult['log_response'], $time);

                        if ($chargeResult['success'] == TRUE) {
                            # Цэнэглэгдсэн мөнгөн дүн болон хувийг хадгалах
                            $bankOrder->charge_amount = $chargeResult['transferred'];
                            $bankOrder->percent = $chargeResult['percent'];
                            if ($orderMobile) {
                                $bankOrder->order_mobile = $orderMobile;
                            }
                            $bankOrder->save();
                            if ($customer) {
                                if ($ADshop) {
                                    TransactionTable::setRechargeAssignment(PaymentTypeTable::DEALER_AD, BankTable::SAVINGS, $bankOrder->bank_account, $bankOrder->order_id, $bankOrder->order_date, $bankOrder->order_p, $bankOrder->order_type, $bankOrder->order_amount, $bankOrder->order_s);
                                } else {
                                    TransactionTable::setRechargeAssignment(PaymentTypeTable::DEALER, BankTable::SAVINGS, $bankOrder->bank_account, $bankOrder->order_id, $bankOrder->order_date, $bankOrder->order_p, $bankOrder->order_type, $bankOrder->order_amount, $bankOrder->order_s);
                                }
                            } else {
                                try {
                                    if ($ADshop) {
                                        TransactionTable::setDealerAssignment(PaymentTypeTable::DEALER_AD, BankTable::SAVINGS, $bankOrder->bank_account, $bankOrder->order_id, $bankOrder->order_date, $bankOrder->order_p, $bankOrder->order_type, $bankOrder->order_amount, $bankOrder->order_s);
                                    } else {
                                        TransactionTable::setDealerAssignment(PaymentTypeTable::DEALER, BankTable::SAVINGS, $bankOrder->bank_account, $bankOrder->order_id, $bankOrder->order_date, $bankOrder->order_p, $bankOrder->order_type, $bankOrder->order_amount, $bankOrder->order_s);
                                    }
                                } catch (\Exception $e) {

                                }
                            }
                            if ($SD || $ADshop) {
                                $bankOrder->status = self::STAT_SUCCESS;
                                $bankOrder->save();
                            } else {
                                # Зарлага үүсгэх
                                $outcomeOrderId = self::reoutcome($bankOrder, $dealer, null, $dealerAgent, $chargeResult['percent']);
                                if ($outcomeOrderId) {
                                    $bankOrder->status = self::STAT_SUCCESS;
                                    $bankOrder->sales_order_id = $outcomeOrderId;
                                    $bankOrder->save();
                                    continue;
                                } else {
                                    $bankOrder->status = self::STAT_FAILED_OUTCOME;
                                    $bankOrder->save();
                                    self::notifyOperators($bankOrder);
                                    continue;
                                }
                            }
                        } else {
                            if ($chargeResult['error_code'] == self::STAT_FAILED_MAX_AMOUNT) {
                                $bankOrder->status = self::STAT_FAILED_MAX_AMOUNT;
                            } elseif ($chargeResult['error_code'] == self::STAT_FAILED_MIN_AMOUNT) {
                                $bankOrder->status = self::STAT_FAILED_MIN_AMOUNT;
                            } else {
                                $bankOrder->status = self::STAT_FAILED_CHARGE;
                            }
                            $bankOrder->save();
                            self::notifyOperators($bankOrder);
                            continue;
                        }
                    } else {
                        $bankOrder->status = self::STAT_FAILED_DEALER;
                        $bankOrder->save();
                        self::notifyOperators($bankOrder);
                        continue;
                    }
                } else {
                    if ($bankOrder->canReCharge() && $bankOrder->try_count < self::MAX_TRY_COUNT) {
                        $bankOrder->status = self::STAT_NEW;
                        $bankOrder->save();
                    }
                    //used to log here...
                }
            } catch (\Exception $ex) {
                $bankOrder->status = self::STAT_FAILED;
                $bankOrder->save();
            }
        }

        return TRUE;
    }

    /**
     * Дахин цэнэглэлт AD shop,SD
     *
     * @param $bankOrder
     * @param $type
     * @return boolean
     * @throws Doctrine_Manager_Exception
     */
    public static function rechargeSMSApi($bankOrder, $type)
    {
        if ($bankOrder instanceof BankSavings) {
            if (!$bankOrder->canReCharge()) {
                return FALSE;
            }
        } else {
            return FALSE;
        }
        $chargeResult = null;
        $pdo = Doctrine_Manager::connection()->getDbh();
        $sql = "UPDATE bankgw.bank_savings
              SET status = '" . self::STAT_PROCESS . "'
              WHERE id = '" . $bankOrder['id'] . "'
              LIMIT 1";
        $affectedRows = $pdo->exec($sql);
        if ($affectedRows == 0) {
            return FALSE;
        }
        $bankOrder->status = self::STAT_PROCESS;
        $bankOrder->try_count++;

        # Цэнэглэлт хийх
        $logId = LogTools::setLogSavingsCharge($bankOrder->id);
        $time = -time();
        if ($type == "SD") {
            $chargeResult = BaseSms::chargeSdDealer(str_replace("SD", "", $bankOrder->charge_mobile), $bankOrder->order_amount, 'STATE');
        } elseif ($type == "AD") {
            $chargeResult = BaseSms::chargeAdDealer($bankOrder->charge_mobile, $bankOrder->order_amount, 'STATE');
        }
        $time += time();
        LogTools::updateLogSavingsCharge($logId, $chargeResult['log_request'], $chargeResult['log_response'], $time);

        if ($chargeResult['success'] == TRUE) {
            if ($type == "AD") {
                TransactionTable::setRechargeAssignment(PaymentTypeTable::DEALER_AD, BankTable::SAVINGS, $bankOrder->bank_account, $bankOrder->order_id, $bankOrder->order_date, $bankOrder->order_p, $bankOrder->order_type, $bankOrder->order_amount, $bankOrder->order_s);
            } else {
                TransactionTable::setRechargeAssignment(PaymentTypeTable::DEALER, BankTable::SAVINGS, $bankOrder->bank_account, $bankOrder->order_id, $bankOrder->order_date, $bankOrder->order_p, $bankOrder->order_type, $bankOrder->order_amount, $bankOrder->order_s);
            }
            # Цэнэглэгдсэн мөнгөн дүн хадгалах
            $bankOrder->charge_amount = $bankOrder->order_amount;
            $bankOrder->status = self::STAT_SUCCESS;
            $bankOrder->save();
            return TRUE;
        } else {
            if ($chargeResult['error_code'] == self::STAT_FAILED_MAX_AMOUNT) {
                $bankOrder->status = self::STAT_FAILED_MAX_AMOUNT;
            } elseif ($chargeResult['error_code'] == self::STAT_FAILED_MIN_AMOUNT) {
                $bankOrder->status = self::STAT_FAILED_MIN_AMOUNT;
            } else {
                $bankOrder->status = self::STAT_FAILED_CHARGE;
            }
            $bankOrder->save();
        }
        return false;
    }

    /**
     * MX  цэнэглэлт
     *
     * @param null $bankOrder
     * @param int $limit
     * @return boolean
     * @throws Doctrine_Manager_Exception
     * @throws Doctrine_Query_Exception
     */
    public static function mxCharge($bankOrder = null, $limit = 50)
    {
        if ($bankOrder instanceof BankSavings) {
            if ($bankOrder->canReCharge()) {
                $bankOrder->status = self::STAT_PROCESS;
                $bankOrder->save();
            }
            $bankOrderRows = array($bankOrder);
        } elseif ($bankOrder) {
            return FALSE;
        } else {
            $bankOrderRows = self::updateForCharge(array(BankSavingsAccountTable::ACCOUNT_MOBIXPRESS), 'ADD', $limit);
        }

        foreach ($bankOrderRows as $bankOrder) {
            try {
                if (in_array($bankOrder->status, array(self::STAT_FAILED_CHARGE, self::STAT_FAILED))) {
                    $bankOrder->status = self::STAT_PROCESS;
                    $bankOrder->save();
                }
                if (substr($bankOrder->order_p, 0, 2) != "MX" && substr($bankOrder->order_p, 0, 2) != "МХ") {
                    //continue;
                }
                if ($bankOrder->status == self::STAT_PROCESS) {
                    $bankOrder->try_count++;
                    $bankOrder->status = self::STAT_PROCESS;
                    $bankOrder->save();

                    # Цэнэглэлт хийх
                    $caller = new MxCharge();
                    $caller->setBankId(VendorCore::BANK_SAVINGS);
                    $caller->setOrderId($bankOrder['id']);
                    $caller->setXml($bankOrder->charge_mobile, $bankOrder->order_amount, substr($bankOrder->order_p, 12));
                    $caller->call();
                    $caller->setAttr();
                    $chargeResult = AppTools::xmlToArray($caller->getXmlResponseRaw());
                    /*
                      Array
                      (
                      [Code] => 3311
                      [Info] => Success
                      [Description] => Done
                      )
                     */

                    if ($chargeResult['Code'] == 3311) {
                        # Цэнэглэгдсэн мөнгөн дүн болон хувийг хадгалах
                        $bankOrder->charge_amount = $bankOrder->order_amount;
                        $bankOrder->status = self::STAT_SUCCESS;
                        $bankOrder->save();
                    } else {
                        $bankOrder->status = self::STAT_FAILED_CHARGE;
                        $bankOrder->save();
                        // self::notifyOperators($bankOrder);
                        continue;
                    }
                } else {
                    if ($bankOrder->canReCharge() && $bankOrder->try_count < self::MAX_TRY_COUNT) {
                        $bankOrder->status = self::STAT_NEW;
                        $bankOrder->save();
                    }
                    //used to log here...
                }
            } catch (\Exception $ex) {
                $bankOrder->status = self::STAT_FAILED;
                $bankOrder->save();
            }
        }

        return TRUE;
    }

    /**
     * Төлөлт оруулах
     *
     * @param null $bankOrder
     * @param int $limit
     * @return boolean
     * @throws Doctrine_Manager_Exception
     * @throws Doctrine_Query_Exception
     */
    public static function callPayment($bankOrder = null, $limit = 50)
    {
        if ($bankOrder instanceof BankSavings) {
            if ($bankOrder->canReCharge()) {
                $bankOrder->status = self::STAT_PROCESS;
                $bankOrder->save();
            }
            $bankOrderRows = array($bankOrder);
        } elseif ($bankOrder) {
            return FALSE;
        } else {
            $bankOrderRows = self::updateForCharge(array(BankSavingsAccountTable::ACCOUNT_CALLPAYMENT), 'ADD', $limit);
        }

        foreach ($bankOrderRows as $bankOrder) {
            try {
                if (in_array($bankOrder->status, array(self::STAT_FAILED_CHARGE, self::STAT_FAILED))) {
                    $bankOrder->status = self::STAT_PROCESS;
                    $bankOrder->save();
                }
                if ($bankOrder->status == self::STAT_PROCESS) {
                    $bankOrder->try_count++;

                    $logId = LogTools::setLogSavingsChargeCallPayment($bankOrder->id);

                    $time = -time();
                    # төлөлт оруулах
                    $params = array(
                        'transDate' => date('Y-m-d', strtotime($bankOrder['order_date'])),
                        'amount' => $bankOrder['order_amount'],
                        'transValue' => $bankOrder['order_p'],
                        'transAccount' => $bankOrder['bank_account'],
                        'transType' => $bankOrder['order_type'],
                        'transNumber' => $bankOrder['order_id'],
                        'bankType' => VendorCore::BANK_SAVINGS,
                    );
                    $chargeResult = CallPayment::charge($params);
                    $time += time();

                    LogTools::updateLogSavingsChargeCallPayment($logId, $chargeResult['log_request'], $chargeResult['log_response'], $time);

                    if ($chargeResult['success'] == TRUE) {
                        # Цэнэглэгдсэн мөнгөн дүн хадгалах
                        $bankOrder->charge_amount = $bankOrder->order_amount;
                        $bankOrder->status = self::STAT_SUCCESS;
                        $bankOrder->save();
                    } else {
                        $bankOrder->status = self::STAT_FAILED_CHARGE;
                        $bankOrder->save();
                        continue;
                    }
                } else {
                    if ($bankOrder->canReCharge() && $bankOrder->try_count < self::MAX_TRY_COUNT) {
                        $bankOrder->status = self::STAT_NEW;
                        $bankOrder->save();
                    }
                    //used to log here...
                }
            } catch (\Exception $ex) {
                $bankOrder->status = self::STAT_FAILED;
                $bankOrder->save();
            }
        }

        return TRUE;
    }

    /**
     * Барааны дансны хуулга хадгалах
     *
     * @param null $bankOrder
     * @param int $limit
     * @return boolean
     * @throws Doctrine_Manager_Exception
     * @throws Doctrine_Query_Exception
     */
    public static function productPayment($bankOrder = null, $limit = 50)
    {
        if ($bankOrder instanceof BankSavings) {
            if ($bankOrder->canReCharge()) {
                $bankOrder->status = self::STAT_PROCESS;
                $bankOrder->save();
            }
            $bankOrderRows = array($bankOrder);
        } elseif ($bankOrder) {
            return FALSE;
        } else {
            $bankOrderRows = self::updateForCharge(array(BankSavingsAccountTable::ACCOUNT_MOBICOM_ALL), 'ADD', $limit);
        }

        foreach ($bankOrderRows as $bankOrder) {
            try {
                if (in_array($bankOrder->status, array(self::STAT_FAILED_CHARGE, self::STAT_FAILED))) {
                    $bankOrder->status = self::STAT_PROCESS;
                    $bankOrder->save();
                }
                if ($bankOrder->status == self::STAT_PROCESS) {
                    $bankOrder->try_count++;
                    $transaction = TransactionTable::insert(BankTable::SAVINGS, $bankOrder['bank_account'], $bankOrder['order_id'], $bankOrder['order_date'], $bankOrder['order_p'], $bankOrder['order_type'], $bankOrder['order_amount'], $bankOrder['order_s']);
                    if ($transaction) {
                        # Цэнэглэгдсэн мөнгөн дүн болон хувийг хадгалах
                        $bankOrder->charge_amount = $bankOrder->order_amount;
                        $bankOrder->status = self::STAT_SUCCESS;
                        $bankOrder->save();
                    } else {
                        $bankOrder->status = self::STAT_FAILED_CHARGE;
                        $bankOrder->save();
                        continue;
                    }
                } else {
                    if ($bankOrder->canReCharge() && $bankOrder->try_count < self::MAX_TRY_COUNT) {
                        $bankOrder->status = self::STAT_NEW;
                        $bankOrder->save();
                    }
                    //used to log here...
                }
            } catch (\Exception $ex) {
                $bankOrder->status = self::STAT_PROCESS;
                $bankOrder->save();
            }
        }

        return TRUE;
    }

    public static function notifyOperators($bankOrder)
    {
//        $mailer = sfContext::getInstance()->getMailer();
//
//        $from = 's.alarm@ntc.mn';
//        $to = array('altantulga@mobicom.mn');
//        $subject = '[Dealer alarm] ' . $bankOrder->order_id;
//        $body = 'Сайн байна уу?<br><br>
//                Шалтгаан: <b>' . self::getStatusName($bankOrder->status) . '</b><br><br>
//                Дараах цэнэглэлт амжилтгүй боллоо:<br>
//                Гүйлгээний дугаар: <b>' . $bankOrder->order_id . '</b><br>
//                Дансны дугаар: <b>' . $bankOrder->bank_account . '</b><br>
//                Цэнэглэх дугаар: <b>' . $bankOrder->charge_mobile . '</b><br>
//                Тушаасан дүн: <b>' . $bankOrder->charge_amount . '</b><br>
//                Хуулганы огноо: <b>' . $bankOrder->order_date . '</b><br>';
//
//        $message = Swift_Message::newInstance()
//                ->setPriority(1)
//                ->setFrom($from, 'Dealer Alarm')
//                ->setSubject($subject)
//                ->setBody($body, 'text/html')
//                ->setTo($to);
//        try {
//            $res = $mailer->send($message);
//        } catch (Swift_TransportException $e) {
//            echo $e->getMessage();
//        }
//        LogTools::setLogEmail($subject, $body, $from, $to);
    }

    /**
     * Дахин зарлага хийх /борлуулалтын бүртгэл/
     *
     * @param BankSavings $bankOrder
     * @param array $dealer (code => string, alias => string, mobile => int, user_id => int, sale_percent_mtopup => int)
     * @param date $date
     * @param null $dealerAgent
     * @param int $percent
     * @return boolean
     */
    public static function reoutcome($bankOrder, $dealer, $date = null, $dealerAgent = null, $percent = 0)
    {
        if (!($bankOrder instanceof BankSavings)) {
            return FALSE;
        } elseif ($bankOrder->status == self::STAT_SUCCESS) {
            return FALSE;
        }

        if (!sizeof($dealer) && !sizeof($dealerAgent)) {
            return FALSE;
        }

        if (!$percent) {
            $percent = $bankOrder->percent;
        }
        if ($dealerAgent) {
            $outcomeUserId = BaseSms::DEALER_SYSTEM;
            $dealerCode = $dealerAgent['dealerCode'];
            $dealerAlias = $dealerAgent['locationDesc'];
            $dealerMobile = $bankOrder->charge_mobile;
        } else {
            $outcomeUserId = $dealer['user_id'];
            $dealerCode = $dealer['code'];
            $dealerMobile = $dealer['mobile'];
            $dealerAlias = $dealer['alias'];
        }

        $params = array(
            'vendor' => VendorTable::BANK_SAVINGS,
            'outcomeDate' => $date,
            'percent' => $percent,
            'productPrice' => 1,
            'totalPrice' => $bankOrder->order_amount,
            'paid' => $bankOrder->order_amount,
            'customerName' => $dealerCode . ' ' . $dealerAlias,
            'customerPhone' => $dealerMobile,
            'outcomeUserId' => $outcomeUserId,
            'quantity' => $bankOrder->charge_amount,
            'vaucher' => $bankOrder->order_id,
            'comment' => $bankOrder->order_p,
            'discount' => $bankOrder->percent,
            'relationId' => $bankOrder->id,
        );
        LogTools::setSmsOutcomeParam(print_r($params, TRUE));
        return BaseSms::insertOutcomeAPI($params);
    }

    /**
     * Цэнэглэх хуулгууд
     * @param $account
     * @param $type
     * @param int $limit
     * @return Doctrine_Collection
     * @throws Doctrine_Manager_Exception
     * @throws Doctrine_Query_Exception
     */
    public static function updateForCharge($account, $type, $limit)
    {
        $whichLog = '';
        if($account == array(self::ACCOUNT_MOBINET_PAYMENT, self::ACCOUNT_CALLPAYMENT)){
            $whichLog = '/bankPaymentLog/savings/bankPaymentLog_'.date('Y-m-d').'.log';
        }else if($account == array(self::ACCOUNT_PRODUCT_MOBINET)){
            $whichLog = '/bankPaymentHBB/savings/bankPaymentHBB_'.date('Y-m-d').'.log';
        }
        $logger = new sfFileLogger(new sfEventDispatcher(), array('file' => sfConfig::get('sf_log_dir') .$whichLog));
        $pdo = Doctrine_Manager::connection()->getDbh();
        // FOR UPDATE ажиллахын тулд AUTO COMMIT идэвхгүй байх ёстой
        $pdo->setAttribute(PDO::ATTR_AUTOCOMMIT, 0);
        $pdo->beginTransaction();
        // Шинэ гүйлгээнүүдийн ID-г авч FOR UPDATE-р түгжинэ
        $ids = Doctrine_Query::create()
            ->select('id')
            ->from('BankSavings')
            ->whereIn('status', array(self::STAT_NEW))
            ->andWhereIn('bank_account', $account)
            ->andWhere('order_type = ?', $type)
            ->limit($limit)
            ->forUpdate(true)
            ->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
        // Олдсон ID-нуудтай гүйлгээнүүдийн төлвийг PROCESS болгоно
        $logger->log('=====updateForCharge $ids: ' . print_r($ids, true), sfFileLogger::INFO);
        if ($ids) {
            Doctrine_Query::create()
                ->update('BankSavings')
                ->set('status', self::STAT_PROCESS)
                ->whereIn('id', $ids)
                ->execute();
            $pdo->commit();
            $pdo->setAttribute(PDO::ATTR_AUTOCOMMIT, 1);
            // Төлөв нь шинэчлэгдсэн гүйлгээнүүдээ буцаах
            $qSelect = Doctrine_Query::create()
                ->from('BankSavings')
                    ->whereIn('id', $ids)
                    ->orderBy('id ASC');
            $logger->log('=====updateForCharge Query:  '. $qSelect->getSQLQuery(), sfFileLogger::INFO);
            return $qSelect->execute();
        } else {
            $pdo->commit();
            $pdo->setAttribute(PDO::ATTR_AUTOCOMMIT, 1);
            return null;
        }
    }

    /**
     * Цэнэглэсэн хуулгуудыг TRANSACTION рүү зөөхөд ашиглав
     *
     * @param $pdo
     * @param int $limit
     * @return Doctrine_Collection
     * @throws Doctrine_Query_Exception
     */
    public static function updateForTransactions($pdo, $limit)
    {
        // FOR UPDATE ажиллахын тулд AUTO COMMIT идэвхгүй байх ёстой
        $pdo->setAttribute(PDO::ATTR_AUTOCOMMIT, 0);
        $pdo->beginTransaction();
        $ids = Doctrine_Query::create()
                        ->select('id')
                        ->from('BankSavings')
                        ->whereNotIn('status', array(self::STAT_PROCESS))
                        ->andWhere('transfer_sap=?', 0)
                        ->andWhere('created_at > ?', date('Y-m-d H:i:s', strtotime("-7 days")))
                        ->andWhere('created_at <= ?', date('Y-m-d H:i:s', time() - 300))
                        ->limit($limit)
                        ->forUpdate(true)
                        ->execute(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
        if ($ids) {
            Doctrine_Query::create()
                ->update('BankSavings')
                ->set('transfer_sap', self::STAT_PROCESS)
                ->whereIn('id', $ids)
                ->execute();
            $pdo->commit();
            $pdo->setAttribute(PDO::ATTR_AUTOCOMMIT, 1);
            $qSelect = Doctrine_Query::create()
                ->from('BankSavings')
                ->whereIn('id', $ids);
            return $qSelect->execute();
        } else {
            $pdo->commit();
            $pdo->setAttribute(PDO::ATTR_AUTOCOMMIT, 1);
            return null;
        }
    }

    /**
     * түр хүлээгдэж байгаа хуулгуудыг авах
     */
    public static function getTempTrans()
    {
        return Doctrine_Query::create()
                        ->from('BankSavings')
                        ->where('status=?', self::STAT_WAIT_TEMP)
                        ->andWhere('order_type = ?', 'ADD')
                        ->andWhere('charge_mobile != ?', '')
                        ->execute();
    }

    public static function updateTempToNewAll($ids)
    {
        $q = Doctrine_Query::create()
                ->update('BankSavings')
                ->set('status', '?', 20)
                ->whereIn('id', $ids)
                ->andWhere('status = ?', self::STAT_WAIT_TEMP)
                ->execute();
    }

    /**
     * Checks if a dealer has charged with exact same amount on a same day.
     * @param $dealerNumber
     * @param $amount
     * @param $date
     * @return Doctrine_Collection
     * @throws Doctrine_Query_Exception
     */
    public static function isDuplicatedToday($dealerNumber, $amount, $date)
    {
        return Doctrine_Query::create()
                        ->from('BankSavings')
                        ->where('charge_mobile = ?', $dealerNumber)
                        ->andWhere('charge_amount = ?', $amount)
                        ->andWhere('order_date = ?', $date)
                        ->andWhereIn('status', array(self::STAT_SUCCESS))
                        ->execute();
    }

    /**
     * Checks if a dealer has charged with exact same amount on a same day.
     * @param int $limit
     * @return void
     * @throws Doctrine_Manager_Exception
     * @throws Doctrine_Query_Exception
     */
    public static function setAssignment($limit)
    {
        $pdo = Doctrine_Manager::connection()->getDbh();
        $transactions = self::updateForTransactions($pdo, $limit);
        $logger = new sfFileLogger(new sfEventDispatcher(), array('file' => sfConfig::get('sf_log_dir') . '/transaction/savings/transfer_'.date('Y-m-d').'.log'));
        $ids = array();
        foreach ($transactions as $transaction) {
            if ($transaction->status == self::STAT_SUCCESS) {
                # odoogoor zuvkhun dealer charge deer l sales uusgej abigaa uchir shalgav
                if ($transaction->sales_order_id) {
                    $dealerChargeType = PaymentTypeTable::DEALER;
                } elseif (BaseSms::isSdDealer($transaction->order_p)) {
                    $dealerChargeType = PaymentTypeTable::DEALER_SD;
                } elseif (BaseSms::isAdShop($transaction->order_p)) {
                    $dealerChargeType = PaymentTypeTable::DEALER_AD;
                } else {
                    $dealerChargeType = 0;
                }
            } else {
                $dealerChargeType = 0;
            }
            $orderType = $transaction->order_type;
            # assignment 
            try {
                $ids[] = $transaction->id;
                $result = TransactionTable::setDealerAssignment($dealerChargeType, BankTable::SAVINGS, $transaction->bank_account, $transaction->order_id, $transaction->order_date, $transaction->order_p, $orderType, $transaction->order_amount, $transaction->order_s);
                $logger->log('STATEBANK' . $transaction->order_id, sfFileLogger::INFO);
            } catch (\Exception $exc) {
                $logger = new sfFileLogger(new sfEventDispatcher(), array('file' => sfConfig::get('sf_log_dir') . '/dealerTransaction.log'));
                $logger->log($transaction->order_id . 'STATEBANK' . $exc->getMessage(), sfFileLogger::ERR);
            }
        }
        if (count($ids)) {
            try {
                # transwered
                $sql = "UPDATE bankgw.bank_savings
              SET transfer_sap = 1
              WHERE id IN(" . implode(',', $ids) . ")
              ";
                $pdo->exec($sql);
            } catch (Exception $exc) {
                $logger->log('STATEBANK-UPDATE' . $exc->getMessage(), sfFileLogger::ERR);
            }
        }
    }

    /**
     * Гүйлгээний утгаас гэрээний дугаарыг олж,
     * Биллийн мэдээллийг татаж bankpayment table -д оруулах
     * CX рүү оруулах төлөлтүүд
     * @param Object $bankOrder
     * @param Boolean $redirectCall (Postpaid tulult bish bol Prepaid shiljuuleh)
     * @param int $limit
     * @return boolean
     * @throws Doctrine_Manager_Exception
     * @throws Doctrine_Query_Exception
     */
    public static function bankPayment($bankOrder = null, $redirectCall = null, $limit = 50)
    {
        $logger = new sfFileLogger(new sfEventDispatcher(), array('file' => sfConfig::get('sf_log_dir') . '/bankPaymentLog/savings/bankPaymentLog_'.date('Y-m-d').'.log'));
        $logger->log('============Started bankPayment Savings================', sfFileLogger::INFO);
        if ($bankOrder instanceof BankSavings) {
            if ($bankOrder->canReCharge()) {
                $bankOrder->status = self::STAT_PROCESS;
                $bankOrder->save();
            }
            $bankOrderRows = array($bankOrder);
        } elseif ($bankOrder) {
            return FALSE;
        } else {
            $bankOrderRows = self::updateForCharge(array(self::ACCOUNT_MOBINET_PAYMENT, self::ACCOUNT_CALLPAYMENT), "ADD", $limit);
        }
        $logger->log('Total count: ' . count($bankOrderRows), sfFileLogger::INFO);
        echo 'bankPayment count: '.count($bankOrderRows).'</br>';
        $count = 0;
        if(count($bankOrderRows)>0){
        foreach ($bankOrderRows as $bankOrder) {
            try {
                $count++;
                $bill = $phoneNumber = $contractNumber = $contractName = $statusComment = null;
                $contractAmount = $billCycle = $paymentCode = 0;
                if (in_array($bankOrder->status, array(self::STAT_FAILED_CHARGE, self::STAT_FAILED))) {
                    $bankOrder->status = self::STAT_PROCESS;
                    $bankOrder->save();
                }
                $logger->log($bankOrder->order_id . ' count: '.$count, sfFileLogger::INFO);
                $logger->log('Order Id: '.$bankOrder->order_id . ', Guilgeenii utga: ' . $bankOrder->order_p, sfFileLogger::INFO);

                $numbers = array();
                $matches = array();
                # mobile bankaar shiljuulsen dugaariig avch hayah
                $txnDesc = preg_replace("/\([0-9]{8}\)/", "", $bankOrder->order_p);
                # Утасны дугаар, гэрээний дугаараас урт тоог хасах
                $txnDesc = preg_replace("/[0-9]{9,}/", "", $txnDesc);
                //preg_match_all("/[0-9]+/", $txnDesc, $matches);
                preg_match_all("/([9][954][0-9]{6})|(85[0-9]{6})|(591[0-9]{5})|([7][75][0-9]{6})|(633[0-9]{5})|([12346][0-9]{7})/", $txnDesc, $matches);
                foreach ($matches as $numberArr) {
                    foreach ($numberArr as $number) {
                        $numbers[] = trim($number);
                    }
                    break;
                }
                $type = 0;
                if ($bankOrder->getBankAccount() == self::ACCOUNT_CALLPAYMENT) {
                    $type = BankpaymentTable::TYPE_CALL_PAYMENT;
                    $limit = sfConfig::get('app_bankpayment_gsm_limit');
                } elseif (in_array($bankOrder->getBankAccount(), array(self::ACCOUNT_MOBINET_PAYMENT, self::ACCOUNT_PRODUCT_MOBINET))) {
                    $type = BankpaymentTable::TYPE_MOBINET;
                    $limit = sfConfig::get('app_bankpayment_nsl_limit');
                } else {
                    continue;
                }
                $contractNumbers = $phoneNumbers = array();
                foreach ($numbers as $number) {
                    $number = trim($number);
                    if ($number) {
                        if (AppTools::isContractNumber($number)) {
                            $contractNumbers[] = $number;
                        }
                        if ($type == BankpaymentTable::TYPE_CALL_PAYMENT) {
                            if (AppTools::isNumber($number) || AppTools::isMobinetHHB($number)) {
                                $phoneNumbers[] = $number;
                            }
                        } else if (AppTools::isNumberMobinet($number)) {
                            $phoneNumbers[] = $number;
                            break;
                        }
                    }
                }
                $logger->log($bankOrder->order_id . ' $phoneNumbers', sfFileLogger::INFO);
                $phoneNumbers = array_unique($phoneNumbers);
                $contractNumbers = array_unique($contractNumbers);
                # guilgeenii utgaas gereenii dugaar,utasnii dugaar oldoogui bol mobile banknii dugaar shalgah
                if ($type == BankpaymentTable::TYPE_CALL_PAYMENT && count($contractNumbers) == 0 && count($phoneNumbers) == 0) {
                    preg_match("/\([0-9]{8}\)/", $bankOrder->order_p, $matches);
                    foreach ($matches as $numberArr) {
                        if (AppTools::isNumber(trim($numberArr, '()'))) {
                            $phoneNumbers[] = trim($numberArr, '()');
                        }
                        break;
                    }
                }
                $insertBankpayment = false;
                $logger->log($bankOrder->order_id . ' $insertBankpayment', sfFileLogger::INFO);
                if (count($contractNumbers) == 1 || count($phoneNumbers) == 1) {
                    $phoneNumber = isset($phoneNumbers[0]) ? $phoneNumbers[0] : 0;
                    $contractNumber = isset($contractNumbers[0]) ? $contractNumbers[0] : 0;
                    if ($phoneNumber) {
                        $logger->log($bankOrder->order_id .', PhoneNumber: ' . $phoneNumber, sfFileLogger::INFO);
                        $bill = PostGateway::getBillInfo($phoneNumber);
                    } else if ($contractNumber) {
                        $logger->log($bankOrder->order_id .', ContractNumber: ' . $contractNumber, sfFileLogger::INFO);
                        $bill = PostGateway::getBillInfo(0, $contractNumber);
                    }
                    $logger->log($bankOrder->order_id . ' $bill' . print_r($bill, true), sfFileLogger::INFO);
                    if ($bill) {
                        if ($bill['Code'] === "0") {
                            if ($contractNumber && $phoneNumbers && $bill['AccountNo'] !== $contractNumber) {
                                $statusComment = "Гэрээний дугаар зөрүүтэй";
                                $phoneNumber = $contractNumber = '';
                                $status = BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE;
                            } else {
                                $contractNumber = $bill['AccountNo'];
                                $billCycle = $bill['BillCycleCode'];
                                $contractAmount = doubleval($bill['CurrentBalance']);
                                $accountInfo = PostGateway::getAccountInfo($contractNumber);
                                $contractName = $accountInfo['AccountName'];
                                if (floatval(strval($contractAmount - $limit)) <= floatval(strval($bankOrder->order_amount)) &&
                                    floatval(strval($bankOrder->order_amount)) <= floatval(strval($contractAmount + $limit))) {
                                    $status = BankpaymentTable::STAT_NEW;
                                } else {
                                    $status = BankpaymentTable::STAT_BANKPAYMENT_AMOUNT;
                                }
                            }
                        } else {
                            $statusComment = $bill['Info'];
                            $status = BankpaymentTable::STAT_FAILED_BILL_INFO;
                        }
                    } elseif ($contractNumber) {
                        $status = BankpaymentTable::STAT_FAILED_BILL_INFO;
                    } else {
                        $statusComment = "Bill info not ";
                        $status = BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE;
                        $logger->log($bankOrder->order_id . ' $statusComment' . $statusComment, sfFileLogger::INFO);
                    }
                } elseif (count($contractNumbers) == 0 && count($phoneNumbers) == 0) {
                    $statusComment = "Гүйлгээний утга буруу";
                    $status = BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE;
                // Олон дугаартай үед нэг гэрээний дугаартай эсэхийг шалгах
                } elseif (count($phoneNumbers) > 1) {
                    $success = 1;
                    $accountNos = array();
                    foreach ($phoneNumbers as $phoneNumber) {
                        var_dump($phoneNumber);
                        $bill = PostGateway::getBillInfo($phoneNumber);
                        if ($bill) {
                            if ($bill['Code'] === "0") {
                                $accountNos[] = $bill['AccountNo'];
                                $billCycle = $bill['BillCycleCode'];
                                $contractAmount = doubleval($bill['CurrentBalance']);
                            } else {
                                $success = 0;
                            }
                        } else {
                            $success = 0;
                        }
                    }
                    if ($success) {
                        $contractNumbers = array_unique($accountNos);
                        if (count($contractNumbers) > 1) {
                            $statusComment = "Олон дугаартай";
                            $status = BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE;
                            $contractAmount = 0;
                            $contractName = '-';
                        } else {
                            $contractNumber = $contractNumbers[0];
                            $accountInfo = PostGateway::getAccountInfo($contractNumber);
                            $contractName = $accountInfo['AccountName'];
                            if (floatval(strval($contractAmount - $limit)) <= floatval(strval($bankOrder->order_amount)) &&
                                floatval(strval($bankOrder->order_amount)) <= floatval(strval($contractAmount + $limit))) {
                                $status = BankpaymentTable::STAT_NEW;
                            } else {
                                $status = BankpaymentTable::STAT_BANKPAYMENT_AMOUNT;
                            }
                            $phoneNumber = $phoneNumbers[0];
                        }
                    } else {
                        $statusComment = "Олон дугаартай";
                        $status = BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE;
                    }
                } else {
                    $status = BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE;
                }
                # Hereglegch oldohgui bol HBB shalgah
                if (!in_array($status, array(BankpaymentTable::STAT_NEW, BankpaymentTable::STAT_BANKPAYMENT_AMOUNT))) {
                    if ($redirectCall) {
                        return false;
                    } else {
                        # Guilgeenii utgaas medeelel oldoogui bol HBB Prepaid tulult shalgah
                        $insertBankpayment = self::bankPaymentHBB($bankOrder, TRUE);
                    }
                }

                $logger->log($bankOrder->order_id . ' $status: ' . $status.' $statusComment: ' . $statusComment, sfFileLogger::INFO);
                # burtgeegui bol burtgeh
                if (!$insertBankpayment) {
                    $logger->log($bankOrder->order_id . ' burtgeh', sfFileLogger::INFO);
                    $data = array();
                    $data['vendor_id'] = VendorTable::BANK_SAVINGS;
                    $data['bank_order_id'] = $bankOrder->id;
                    $data['type'] = $type;
                    $data['status'] = $status;
                    $data['status_comment'] = $statusComment;
                    $data['number'] = $phoneNumber;
                    $data['contract_number'] = $contractNumber;
                    $data['contract_name'] = $contractName;
                    $data['bill_cycle'] = $billCycle;
                    $data['contract_amount'] = $contractAmount;
                    $data['credit_control'] = 123;
                    BankpaymentTable::insert($data);
                    $bankOrder->status = BankpaymentTable::STAT_SUCCESS;
                    $bankOrder->save();
                    unset($bankOrder);
                }
            } catch (\Exception $ex) {
                $bankOrder->status = BankpaymentTable::STAT_PROCESS;
                $bankOrder->save();
                $logger->log('Error: '.$bankOrder->order_id .' Error message: '.$ex, sfFileLogger::ERR);
            }
        }
        }
        $logger->log('=============== Ended bankPayment Savings===============', sfFileLogger::INFO);
        return TRUE;
    }

    /**
     * Мобинэт HBB prepaid төлөлтийн дансны гүйлгээнүүдийг
     *  дамжуулах
     * @param null $bankOrder
     * @param Boolean $redirectCall (Prepaid tulult bish bol Postruu shiljuuleh)
     * @param int $limit
     * @return boolean
     * @throws Doctrine_Manager_Exception
     * @throws Doctrine_Query_Exception
     */
    public static function bankPaymentHBB($bankOrder = null, $redirectCall = null, $limit = 50)
    {
        $logger = new sfFileLogger(new sfEventDispatcher(), array('file' => sfConfig::get('sf_log_dir') . '/bankPaymentHBB/savings/bankPaymentHBB_'.date('Y-m-d').'.log'));
        $logger->log('============Started bankPaymentHBB Savings================', sfFileLogger::INFO);

        if ($bankOrder instanceof BankSavings) {
            if ($bankOrder->canReCharge()) {
                $bankOrder->status = self::STAT_PROCESS;
                $bankOrder->save();
            }
            $bankOrderRows = array($bankOrder);
        } elseif ($bankOrder) {
            return FALSE;
        } else {
            $bankOrderRows = self::updateForCharge(array(self::ACCOUNT_PRODUCT_MOBINET), "ADD", $limit);
        }
        $logger->log('Total count: ' . count($bankOrderRows), sfFileLogger::INFO);
        $count = 0;
        echo 'bankPaymentHBB count =>'.count($bankOrderRows).'</br>';
        if(count($bankOrderRows)>0){
        foreach ($bankOrderRows as $bankOrder) {
            try {
                $count++;
                $contractNumber = $contractName = null;
                $contractAmount = $billCycle = $paymentCode = 0;
                $username = $contractName = '';
                $logger->log($bankOrder->order_id . ' count: '.$count, sfFileLogger::INFO);
                $logger->log('Order Id: '.$bankOrder->order_id . ', Guilgeenii utga: ' . $bankOrder->order_p, sfFileLogger::INFO);
                $logger->log($bankOrder->order_id . ' status: ' . $bankOrder->status, sfFileLogger::INFO);
                if (in_array($bankOrder->status, array(self::STAT_FAILED_CHARGE, self::STAT_FAILED))) {
                    $bankOrder->status = self::STAT_PROCESS;
                    $bankOrder->save();
                }
                $logger->log($bankOrder->order_id . ' status1:' . $bankOrder->status, sfFileLogger::INFO);
                $insertBankpayment = false;
                # MOBINET WIFI shalgah
                $wifiRegex = "/WIFI-(([9][954][0-9]{6})|(85[0-9]{6}))-([0-9_a-zA-Z]{1,20})-*/";
                if (preg_match($wifiRegex, $bankOrder->order_p, $matches)) {
                    $logger->log('--WIFI--=', sfFileLogger::INFO);
                    $type = BankpaymentTable::TYPE_WIFI;
                    $phoneNumber = $matches[1];
                    $card = $matches[4];
                    $username = $phoneNumber;
                    # TEST hiih dugaaruudiig l zuvshuuruv
                    //if (in_array($phoneNumber, array('94300074', '94300115'))) {
                    $result = WifiOnlineGateway::chargeCard($phoneNumber, $card, "bankgw_savings");
                    //}
                    if (isset($result['Code']) && $result['Code'] == 0) {
                        $status = BankpaymentTable::STAT_SUCCESS;
                    } else {
                        $statusComment = "Амжилтгүй(" . $result ['Info'] . ")";
                        $status = BankpaymentTable::STAT_FAILED_CHARGE;
                    }
                } else {
                    $keyword = BankpaymentTable::findHbbContract($bankOrder->order_p);
                    if (!$keyword) {
                        $keyword = BankpaymentTable::findHbbUsername($bankOrder->order_p);
                    }
                    $logger->log($bankOrder->order_id . ' $keyword: ' . $keyword , sfFileLogger::INFO);

                    $type = BankpaymentTable::TYPE_MOBINET_PREPAID;
                    $speed = 0;
                    if ($keyword) {
                        $accountInfo = MobinetGateway::contractInfo($keyword);
                        $logger->log($bankOrder->order_id . ' $accountInfo:' . print_r($accountInfo, true), sfFileLogger::INFO);

                        if (isset($accountInfo['id']) && $accountInfo['id']) {
                            if (AppTools::isPostHbbContract($accountInfo['contract'])) {
                                $status = BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE;
                            } else {
                                $contractNumber = $accountInfo['contract'];
                                $username = $accountInfo['username'];
                                $speed = $accountInfo['speed'];
                                $contractName = $accountInfo['lastname'] . ' ' . $accountInfo['firstname'];
                                $status = BankpaymentTable::STAT_NEW;
                                unset($accountInfo);
                            }
                        } else {
                            $status = BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE;
                        }
                    } else {
                        $status = BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE;
                    }
                }
                $logger->log($bankOrder->order_id . ' status2:' . $status, sfFileLogger::INFO);
                if ($status == BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE) {

                }
                # Hereglegch oldohgui bol HBB shalgah
                if ($status !== BankpaymentTable::STAT_NEW) {
                    $logger->log($bankOrder->order_id . ' status3:' . $status, sfFileLogger::INFO);
                    if ($redirectCall) {
                        return false;
                    } else {
                        # Guilgeenii utgaas medeelel oldoogui bol Postpaid tulult shalgah
                        $insertBankpayment = self::bankPayment($bankOrder, TRUE);
                    }
                }
                $logger->log($bankOrder->order_id . ' status4:' . $status, sfFileLogger::INFO);

                if (!$insertBankpayment) {
                    $logger->log($bankOrder->order_id . ' status5:' . $status, sfFileLogger::INFO);
                    try {
                        $data = array();
                        $data['vendor_id'] = VendorTable::BANK_SAVINGS;
                        $data['bank_order_id'] = $bankOrder->id;
                        $data['type'] = $type;
                        $data['status'] = $status;
                        $data['number'] = $username;
                        $data['contract_number'] = $contractNumber;
                        $data['contract_name'] = $contractName;
                        $data['contract_amount'] = $contractAmount;

                        $bankpayment = BankpaymentTable::insert($data);
                        if ($bankpayment && $type = BankpaymentTable::TYPE_MOBINET_PREPAID) {
                            BankpaymentMobinetTable::insert($bankpayment->id, $speed);
                        }
                        $bankOrder->status = self::STAT_SUCCESS;
                        $bankOrder->save();
                    } catch (Exception $exc) {
                        $logger->log('$insertHBBBankpayment Savings Error: '.$bankOrder->order_id .' Error message: '.$exc, sfFileLogger::ERR);
                    }
                }

                unset($bankOrder);
            } catch (\Exception $ex) {
                $bankOrder->status = self::STAT_PROCESS;
                $bankOrder->save();
                $logger->log($bankOrder->order_id . ' Error: ' . $ex, sfFileLogger::INFO);
            }
        }
        }
        $logger->log('============Ended bankPaymentHBB Savings================', sfFileLogger::INFO);
        return TRUE;
    }

    public static function retrieveByTran($order_id, $order_type, $order_amount, $order_date)
    {
        $q = Doctrine_Query::create()
                ->from('BankSavings')
                ->where('order_id = ?', $order_id)
                ->addWhere('order_type = ?', $order_type)
                ->addWhere('order_amount = ?', $order_amount)
                ->addWhere('order_date = ?', $order_date);

        return $q->fetchOne();
    }
    
    public static function bankPaymentFromTransaction($bankOrder = null, $redirectCall = null, $limit = 50)
    {
        $logger = new sfFileLogger(new sfEventDispatcher(), array('file' => sfConfig::get('sf_log_dir') . '/bankPaymentFromTransaction/savings/bankPaymentFromTransaction_'.date('Y-m-d').'.log'));
        $logger->log('============Started bankPaymentFromTransaction Savings================', sfFileLogger::INFO);
        if ($bankOrder instanceof BankSavings) {
            if ($bankOrder->canReCharge()) {
                $bankOrder->status = self::STAT_PROCESS;
                $bankOrder->save();
            }
            $bankOrderRows = array($bankOrder);
        } elseif ($bankOrder) {
            return FALSE;
        } else {
            $bankOrderRows = self::updateForCharge(array(self::ACCOUNT_MOBINET_PAYMENT, self::ACCOUNT_CALLPAYMENT), "ADD", $limit);
        }
        $logger->log('Total count: ' . count($bankOrderRows), sfFileLogger::INFO);
        echo 'bankPaymentFromTransaction count: '.count($bankOrderRows).'</br>';
        $count = 0;
        if(count($bankOrderRows)>0){
        foreach ($bankOrderRows as $bankOrder) {
            $bill = $phoneNumber = $contractNumber = $contractName = $statusComment = null;
            $contractAmount = $billCycle = $paymentCode = 0;
            if (in_array($bankOrder->status, array(self::STAT_FAILED_CHARGE, self::STAT_FAILED))) {
                $bankOrder->status = self::STAT_PROCESS;
                $bankOrder->save();
            }
            $logger->log($bankOrder->order_id . ' count: '.$count, sfFileLogger::INFO);
            $logger->log('Order Id: '.$bankOrder->order_id . ', Guilgeenii utga: ' . $bankOrder->order_p, sfFileLogger::INFO);

            $numbers = array();
            $matches = array();
            # mobile bankaar shiljuulsen dugaariig avch hayah
            $txnDesc = preg_replace("/\([0-9]{8}\)/", "", $bankOrder->order_p);
            # Утасны дугаар, гэрээний дугаараас урт тоог хасах
            $txnDesc = preg_replace("/[0-9]{9,}/", "", $txnDesc);
            //preg_match_all("/[0-9]+/", $txnDesc, $matches);
            preg_match_all("/([9][954][0-9]{6})|(85[0-9]{6})|(591[0-9]{5})|([7][75][0-9]{6})|(633[0-9]{5})|([12346][0-9]{7})/", $txnDesc, $matches);
            foreach ($matches as $numberArr) {
                foreach ($numberArr as $number) {
                    $numbers[] = trim($number);
                }
                break;
            }
            $type = BankpaymentTable::TYPE_CALL_PAYMENT;
            if ($bankOrder->getBankAccount() == self::ACCOUNT_CALLPAYMENT) {
                $type = BankpaymentTable::TYPE_CALL_PAYMENT;
                $limit = sfConfig::get('app_bankpayment_gsm_limit');
            } elseif (in_array($bankOrder->getBankAccount(), array(self::ACCOUNT_MOBINET_PAYMENT, self::ACCOUNT_PRODUCT_MOBINET))) {
                $type = BankpaymentTable::TYPE_MOBINET;
                $limit = sfConfig::get('app_bankpayment_nsl_limit');
            }
            $contractNumbers = $phoneNumbers = array();
            foreach ($numbers as $number) {
                $number = trim($number);
                if ($number) {
                    if (AppTools::isContractNumber($number)) {
                        $contractNumbers[] = $number;
                    }
                    if ($type == BankpaymentTable::TYPE_CALL_PAYMENT) {
                        if (AppTools::isNumber($number) || AppTools::isMobinetHHB($number)) {
                            $phoneNumbers[] = $number;
                        }
                    } else if (AppTools::isNumberMobinet($number)) {
                        $phoneNumbers[] = $number;
                        break;
                    }
                }
            }
            $logger->log($bankOrder->order_id . ' $phoneNumbers', sfFileLogger::INFO);
            $phoneNumbers = array_unique($phoneNumbers);
            $contractNumbers = array_unique($contractNumbers);
            # guilgeenii utgaas gereenii dugaar,utasnii dugaar oldoogui bol mobile banknii dugaar shalgah
            if ($type == BankpaymentTable::TYPE_CALL_PAYMENT && count($contractNumbers) == 0 && count($phoneNumbers) == 0) {
                preg_match("/\([0-9]{8}\)/", $bankOrder->order_p, $matches);
                foreach ($matches as $numberArr) {
                    if (AppTools::isNumber(trim($numberArr, '()'))) {
                        $phoneNumbers[] = trim($numberArr, '()');
                    }
                    break;
                }
            }
            $insertBankpayment = false;
            $logger->log($bankOrder->order_id . ' $insertBankpayment', sfFileLogger::INFO);
            if (count($contractNumbers) == 1 || count($phoneNumbers) == 1) {
                $phoneNumber = isset($phoneNumbers[0]) ? $phoneNumbers[0] : 0;
                $contractNumber = isset($contractNumbers[0]) ? $contractNumbers[0] : 0;
                if ($phoneNumber) {
                    $logger->log($bankOrder->order_id .', $phoneNumber: ' . $phoneNumber, sfFileLogger::INFO);
                    $bill = PostGateway::getBillInfo($phoneNumber);
                } else if ($contractNumber) {
                    $bill = PostGateway::getBillInfo(0, $contractNumber);
                    $logger->log($bankOrder->order_id .', $contractNumber: ' . $contractNumber, sfFileLogger::INFO);
                }
                $logger->log($bankOrder->order_id . ' $bill' . print_r($bill, true), sfFileLogger::INFO);
                if ($bill) {
                    if ($bill['Code'] === "0") {
                        $logger->log($bankOrder->order_id .' Postpaid number matches.', sfFileLogger::INFO);
                        if ($contractNumber && $phoneNumbers && $bill['AccountNo'] !== $contractNumber) {
                            $statusComment = "Гэрээний дугаар зөрүүтэй";
                            $phoneNumber = $contractNumber = '';
                            $status = BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE;
                        } else {
                            $contractNumber = $bill['AccountNo'];
                            $billCycle = $bill['BillCycleCode'];
                            $contractAmount = doubleval($bill['CurrentBalance']);
                            $accountInfo = PostGateway::getAccountInfo($contractNumber);
                            $contractName = $accountInfo['AccountName'];
                            if (floatval(strval($contractAmount - $limit)) <= floatval(strval($bankOrder->order_amount)) &&
                                    floatval(strval($bankOrder->order_amount)) <= floatval(strval($contractAmount + $limit))) {
                                $status = BankpaymentTable::STAT_NEW;
                            } else {
                                $status = BankpaymentTable::STAT_BANKPAYMENT_AMOUNT;
                            }
                        }
                    } else {
                        $statusComment = $bill['Info'];
                        $status = BankpaymentTable::STAT_FAILED_BILL_INFO;
                    }
                } elseif ($contractNumber) {
                    $status = BankpaymentTable::STAT_FAILED_BILL_INFO;
                } else {
                    $statusComment = "Bill info not ";
                    $status = BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE;
                    $logger->log($bankOrder->order_id . ' $statusComment' . $statusComment, sfFileLogger::INFO);
                }
            } elseif (count($contractNumbers) == 0 && count($phoneNumbers) == 0) {
                $statusComment = "Гүйлгээний утга буруу";
                $status = BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE;
            } else {
                $statusComment = "Олон дугаартай";
                $status = BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE;
            }
            # Hereglegch oldohgui bol HBB shalgah
            if (!in_array($status, array(BankpaymentTable::STAT_NEW, BankpaymentTable::STAT_BANKPAYMENT_AMOUNT))) {
                if ($redirectCall) {
                    return false;
                } else {
                    # Guilgeenii utgaas medeelel oldoogui bol HBB Prepaid tulult shalgah
                    $insertBankpayment = self::bankPaymentHBB($bankOrder, TRUE);
                }
            }

            $logger->log($bankOrder->order_id . ' $status: ' . $status.' $statusComment: ' . $statusComment, sfFileLogger::INFO);
            # burtgeegui bol burtgeh
            if (!$insertBankpayment) {
                $logger->log($bankOrder->order_id . ' burtgeh', sfFileLogger::INFO);
                $data = array();
                $data['vendor_id'] = VendorTable::BANK_SAVINGS;
                $data['bank_order_id'] = $bankOrder->id;
                $data['type'] = $type;
                $data['status'] = $status;
                $data['status_comment'] = $statusComment;
                $data['number'] = $phoneNumber;
                $data['contract_number'] = $contractNumber;
                $data['contract_name'] = $contractName;
                $data['bill_cycle'] = $billCycle;
                $data['contract_amount'] = $contractAmount;
                $data['credit_control'] = 123;
                BankpaymentTable::insert($data);
                $bankOrder->status = BankpaymentTable::STAT_SUCCESS;
                $bankOrder->save();
                unset($bankOrder);
            }
        }
        }
        $logger->log('============Ended bankPaymentFromTransaction Savings================', sfFileLogger::INFO);
        return TRUE;
    }

    /**
     * Candy цэнэглэлт Bankpayment-рүү хийх
     *  дамжуулах
     * @param object bank
     * @param int $limit
     * @return boolean
     * @throws Doctrine_Manager_Exception
     * @throws Doctrine_Query_Exception
     */
    public static function loyaltyBankpayment($bankOrder = null, $limit = 50)
    {
        if ($bankOrder instanceof BankSavings) {
            if (in_array($bankOrder->status, array(
                BankSavingsTable::STAT_FAILED,
                BankSavingsTable::STAT_PROCESS,
                BankSavingsTable::STAT_FAILED_CHARGE,
                BankSavingsTable::STAT_FAILED_OUTCOME))) {
                $bankOrder->status = self::STAT_PROCESS;
                $bankOrder->save();
            }
            $bankOrderRows = array($bankOrder);
        } elseif ($bankOrder) {
            return FALSE;
        } else {
            $bankOrderRows = self::updateForCharge(array(self::ACCOUNT_MOBIFINANCE_CANDY), 'ADD', $limit);
        }
        foreach ($bankOrderRows as $bankOrder) {
            try {
                if (in_array($bankOrder->status, array(self::STAT_FAILED_CHARGE, self::STAT_FAILED))) {
                    $bankOrder->status = self::STAT_PROCESS;
                    $bankOrder->save();
                }

                $txnDesc = preg_replace("/\([0-9]{8}\)/", "", $bankOrder->order_p);
                $chargeNumber = LoyaltyCharge::findCandyLoan($txnDesc);
                if ($chargeNumber) {
                    $loanAmount = null;
                    $cashInAmount = null;
                    $type = null;
                    $isQpay = LoyaltyCharge::checkCandyQpay($txnDesc);
                    if ($isQpay) {
                        $type = BankpaymentTable::TYPE_CANDY_QPAY;
                        self::insertBankpaymentLoyalty($bankOrder, $type, $chargeNumber, $bankOrder->order_amount);
                        $bankOrder->setStatus(BankSavingsTable::STAT_SUCCESS);
                        $bankOrder->save();
                        continue;
                    }
                    $isCandyAgent = LoyaltyCharge::checkCandyAgent($txnDesc);
                    $isCandyAccount = LoyaltyCharge::checkCandyAccount($bankOrder['bank_account'], 'SAVINGS');
                    if ($bankOrder['bank_account'] == self::ACCOUNT_MOBIFINANCE_CANDY) {
                        $loanCheck = LoyaltyCharge::checkLoan($chargeNumber);
                        if ($loanCheck['Code'] !== 0) {
                            $status = self::STAT_FAILED_CHARGE;
                            $bankOrder->setStatus($status);
                            $bankOrder->save();
                            self::insertBankpaymentLoyalty($bankOrder, BankpaymentTable::TYPE_CANDY_CASHIN, $chargeNumber, $bankOrder['order_amount'], '', 4);
                            continue;
                        }
                        // Zeeltei bol
                        if ($loanCheck['Result']['items'][0]['total'] > 0) {
                            $cashInAmount = $bankOrder['order_amount'] - $loanCheck['Result']['items'][0]['total'];
                            $loanAmount = $loanCheck['Result']['items'][0]['total'];
                            if ($cashInAmount < 0) {
                                $cashInAmount = null;
                                $loanAmount = $bankOrder['order_amount'];
                            }
                        } else {
                            $cashInAmount = $bankOrder['order_amount'];
                        }
                    } else {
                        $cashInAmount = $bankOrder['order_amount'];
                    }

                    if ($isCandyAgent && $isCandyAccount) {
                        $loyaltyId = LoyaltyCharge::getCandy($isCandyAgent);
                        if ($loyaltyId != 0) {
                            self::insertBankpaymentLoyalty($bankOrder, BankpaymentTable::TYPE_CANDY_AGENT, $chargeNumber, $bankOrder->order_amount, $loyaltyId);
                        } else {
                            if (!$loanAmount) {
                                self::insertBankpaymentLoyalty($bankOrder, BankpaymentTable::TYPE_CANDY_CASHIN, $chargeNumber, $cashInAmount);
                            } else {
                                if ($cashInAmount > 0) {
                                    $bankpayment = self::insertBankpaymentLoyalty($bankOrder, BankpaymentTable::TYPE_CANDY_CASHIN, $chargeNumber, $cashInAmount);
                                    self::copyBankpaymentLoyalty($bankpayment, $loanAmount, BankpaymentTable::TYPE_CANDY_LOAN, $chargeNumber);
                                } else {
                                    self::insertBankpaymentLoyalty($bankOrder, BankpaymentTable::TYPE_CANDY_LOAN, $chargeNumber, $loanAmount);
                                }
                            }
                        }
                    } else {
                        if (!$loanAmount) {
                            self::insertBankpaymentLoyalty($bankOrder, BankpaymentTable::TYPE_CANDY_CASHIN, $chargeNumber, $cashInAmount);
                        } else {
                            if ($cashInAmount) {
                                $bankpayment = self::insertBankpaymentLoyalty($bankOrder, BankpaymentTable::TYPE_CANDY_CASHIN, $chargeNumber, $cashInAmount);
                                self::copyBankpaymentLoyalty($bankpayment, $loanAmount, BankpaymentTable::TYPE_CANDY_LOAN, $chargeNumber);
                            } else {
                                self::insertBankpaymentLoyalty($bankOrder, BankpaymentTable::TYPE_CANDY_LOAN, $chargeNumber, $loanAmount);
                            }
                        }
                    }
                    $bankOrder->setStatus(BankSavingsTable::STAT_SUCCESS);
                    $bankOrder->save();
                    unset($bankOrder);
                } else {
                    if ($bankOrder['bank_account'] == self::ACCOUNT_MOBIFINANCE_CANDY) {
                        self::insertBankpaymentLoyalty($bankOrder, BankpaymentTable::TYPE_CANDY_LOAN, $chargeNumber, $bankOrder['order_amount'], '', BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE);
                    } else {
                        self::insertBankpaymentLoyalty($bankOrder, BankpaymentTable::TYPE_CANDY_CASHIN, $chargeNumber, $bankOrder['order_amount'], '', BankpaymentTable::STAT_BANKPAYMENT_TRANS_VALUE);
                    }
                    $bankOrder->setStatus(self::STAT_FAILED_CHARGE);
                    $bankOrder->save();
                }
            } catch (\Exception $ex) {
                $bankOrder->setStatus(self::STAT_FAILED);
                $bankOrder->save();
            }
        }

        return TRUE;
    }

    public static function insertBankpaymentLoyalty($bankOrder, $type, $chargeNumber, $amount, $loyaltyId = '', $status = 1) {
        $data = array();
        $data['vendor_id'] = VendorTable::BANK_SAVINGS;
        $data['bank_order_id'] = $bankOrder->id;
        $data['type'] = $type;
        $data['status'] = $status;
        $data['status_comment'] = '';
        $data['number'] = $chargeNumber;
        $data['contract_number'] = $loyaltyId;
        $data['contract_name'] = '';
        $data['bill_cycle'] = '';
        $data['paid_amount'] = $amount;
        $data['contract_amount'] = '';
        $data['credit_control'] = 123;
        $bankpayment = BankpaymentTable::insert($data);
        return $bankpayment;
    }

    public static function copyBankpaymentLoyalty($bankpayment, $amount, $type, $chargeNumber)
    {
        $childCount = (int) BankpaymentTable::getChildCount($bankpayment['id']);
        $values = array();
        $values['parent_id'] = $bankpayment['id'];
        $values['vendor_id'] = $bankpayment['vendor_id'];
        $values['type'] = $type;
        $values['bank_order_id'] = $bankpayment['bank_order_id'];
        $values['child_num'] = ++$childCount;
        $values['paid_amount'] = $amount;
        $values['status'] = BankpaymentTable::STAT_NEW;
        $values['number'] = $chargeNumber;
        BankpaymentTable::insert($values);
    }
}