<?php

/**
 * BlockDate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BANKGW
 * @subpackage model
 * @author     Belbayar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BlockDate extends BaseBlockDate
{

}