<?php

/**
 * DeletedPaymentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeletedPaymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeletedPaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeletedPayment');
    }
}