<?php

/**
 * KhaanTransTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KhaanTransTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object KhaanTransTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('KhaanTrans');
    }

    /**
     *
     *
     * @return object BankSavingsTransTable
     */
    public static function insert($id, $transIds)
    {
        $transition = 'T' . join('T', $transIds);

        $trans = new KhaanTrans();
        $trans->setTransition($transition);
        $trans->save();
        return $transition;
    }

    /**
     *
     * getTransiction
     * @return object BankSavingsTransTable
     */
    public static function getTransiction()
    {
        $transitions = Doctrine_Query::create()
                ->from('KhaanTrans')
                ->where('status = ?', 0)
                ->execute();
        $transition = '';
        foreach ($transitions as $trans) {
            $transition.=$trans['transition'];
            $trans->setStatus(1);
            $trans->save();
        }

        return $transition;
    }

}
