<?php

/**
 * LogCapitronInitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogCapitronInitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogCapitronInitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogCapitronInit');
    }
}