<?php

/**
 * VendorUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VendorUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VendorUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VendorUser');
    }
}