<?php

/**
 * VendorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VendorTable extends Doctrine_Table
{
    
    const MOBIXPRESS = 2;
    const CANDY = 3;
    #
    const ACTIVE = 1;
    const PASSIVE = 2;
    const DELETED = 3;
    const ERROR_CODE = 101;
    const ERROR_INFO = 'Борлуулагчийн мэдээлэл олдсонгүй!';
    #ID
    const VENDOR_VENDEX = 5;
    const VENDOR_QUICKPAY = 6;
    const GOLOMT = 1;
    const BANK_SAVINGS = 8;
    const BANK_KHAAN = 9;
    const BANK_XAC = 10;
    const BANK_TDB = 11;
    const BANK_CAPITAL = 12;
    const BANK_CAPITRON = 13;

	 #type
    const TYPE_BANK = 1;
    /**
     * Returns an instance of this class.
     *
     * @return object VendorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vendor');
    }
	
    /**
     * Нэр
     * 
     * @return array
     */
    public static function getNameById($id)
    {
        $bank = Doctrine_Query::create()
                ->from('Vendor')
                ->where('id =?', $id)
                ->fetchOne();
        if ($bank)
            return $bank->getName();
        return '';
    }

    /**
     * Төлөв
     * 
     * @return array
     */
    public static function getForSelect()
    {
        $row = array();
        $banks = Doctrine_Query::create()
                ->from('Vendor')
                ->where('source_code =?', self::TYPE_BANK)
                ->andWhere('status = ?', self::ACTIVE)
                ->execute();
        foreach ($banks as $key => $bank) {
            $row[$bank['id']] = $bank['name'];
        }
        return $row;
    }


}
