
all:
  is_secure: true
  credentials: [[observ]]

list:
  is_secure: true
  credentials: [[transaction_view,observ]]
  
status:
  is_secure: true
  credentials: [[transaction_view,observ]]

callPayment:
  is_secure: true
  credentials: [call_payment_observ]

callPaymentStatus:
  is_secure: true
  credentials: [call_payment_observ]  

rechargeCallpayment:
  is_secure: true
  credentials: [call_payment_observ]  

callPaymentExcel:
  is_secure: true
  credentials: [call_payment_observ]  